### ISSUE TITLE
Shadow and uniform_input tests fails to pass

### ISSUE THREAD

**Issue by qarmin** [gfx-rs/wgpu#3425] opened 2023-01-26 10:58 UTC
**Description**
Test not pass on my PC

**Repro steps**
`cargo nextest run shadow --no-fail-fast`
prints
```
    Finished test [unoptimized + debuginfo] target(s) in 0.15s
    Starting 1 tests across 17 binaries (75 skipped)
     SIGSEGV [   0.185s] wgpu::example/shadow shadow

--- STDOUT:              wgpu::example/shadow shadow ---

running 1 test

------------
     Summary [   0.185s] 1 tests run: 0 passed, 1 failed, 75 skipped
     SIGSEGV [   0.185s] wgpu::example/shadow shadow
error: test run failed
```

```
cargo nextest run uniform_input --no-fail-fast
```
prints (removed some duplicate)
```
        FAIL [   0.212s] wgpu::wgpu-tests shader::struct_layout::uniform_input

--- STDOUT:              wgpu::wgpu-tests shader::struct_layout::uniform_input ---

running 1 test
test shader::struct_layout::uniform_input ... FAILED

failures:

failures:
    shader::struct_layout::uniform_input

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 43 filtered out; finished in 0.21s


--- STDERR:              wgpu::wgpu-tests shader::struct_layout::uniform_input ---
[2023-01-26T10:55:18Z ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
    	Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x7f41f4c04620, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Structure id 11 decorated as Block for variable in Uniform storage class must follow relaxed uniform buffer layout rules: member 0 is a matrix with stride 8 not satisfying alignment to 16
      %CustomStruct = OpTypeStruct %mat2v2float
    
    
[2023-01-26T10:55:18Z ERROR wgpu_hal::vulkan::instance] 	objects: (type: DEVICE, hndl: 0x7f41f4c04620, name: ?)
thread 'shader::struct_layout::uniform_input' panicked at 'UNEXPECTED TEST FAILURE DUE TO VALIDATION ERROR', wgpu/tests/common/mod.rs:329:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

------------
     Summary [   0.212s] 1 tests run: 0 passed, 1 failed, 75 skipped
        FAIL [   0.212s] wgpu::wgpu-tests shader::struct_layout::uniform_input
error: test run failed

```

**Platform**
wgpu - latest commit - 659f6977051345e4e06ab4832c6f7d268f25a1ad
```
System:
  Host: rafal-H87M-D3H Kernel: 5.19.0-28-generic arch: x86_64 bits: 64
    compiler: N/A Desktop: GNOME v: 43.1 tk: GTK v: 3.24.34 wm: gnome-shell
    dm: GDM3 Distro: Ubuntu 22.10 (Kinetic Kudu)
CPU:
  Info: quad core model: Intel Core i7-4770 bits: 64 type: MT MCP
    arch: Haswell level: v3 rev: 3 cache: L1: 256 KiB L2: 1024 KiB L3: 8 MiB
  Speed (MHz): avg: 2984 high: 3900 min/max: 800/3900 cores: 1: 3729
    2: 3845 3: 900 4: 1900 5: 3813 6: 3900 7: 1900 8: 3890 bogomips: 54279
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    vendor: Sapphire driver: amdgpu v: kernel arch: GCN-4 pcie: speed: 8 GT/s
    lanes: 16 ports: active: HDMI-A-1 empty: DP-1, DP-2, DVI-D-1, HDMI-A-2
    bus-ID: 01:00.0 chip-ID: 1002:67df
  Display: x11 server: X.Org v: 1.21.1.4 with: Xwayland v: 22.1.3
    compositor: gnome-shell driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu display-ID: :0
    screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: HDMI-A-1 mapped: HDMI-A-0 model: Idek Iiyama PL2530H
    res: 1920x1080 dpi: 90 diag: 623mm (24.5")
  OpenGL: renderer: AMD Radeon RX 570 Series (polaris10 LLVM 15.0.2 DRM
    3.47 5.19.0-28-generic) v: 4.6 Mesa 23.0.0-devel (git-980df9ede1)
    direct render: Yes

```

**Comment by teoxoy** [comment] 2023-01-26 11:01
Closing as duplicate of https://github.com/gfx-rs/naga/issues/2034 / https://github.com/gfx-rs/naga/issues/1785

**Closed by teoxoy** 2023-01-26 11:01 UTC
