### ISSUE TITLE
Buffer unaligned uninitialized range

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#2420] opened 2022-01-25 05:44 UTC
**Description**
Got this error:
> thread 'main' panicked at 'Buffer Buffer { raw: 0x149d740000000087, block: Mutex { data: MemoryBlock { memory_type: 0, props: DEVICE_LOCAL | HOST_VISIBLE | HOST_COHERENT | HOST_CACHED, offset: 565248, size: 8192, atom_mask: 0, mapped: false, flavor: Buddy { chunk: 0, index: 3, ptr: Some(0x7f9d39737000), memory: 0xead9370000000008 }, relevant: Relevant } } } has an uninitialized range with an end not aligned to 4 (end was 4926)', /home/kvark/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/f3891fe/wgpu-core/src/command/memory_init.rs:223:17

**Repro steps**
Probably just creating a buffer with size not divisible by 4

**Expected vs observed behavior**
Shouldn't error if that's permitted by the spec.

**Extra materials**
cc @Wumpf 
**Platform**

**Comment by jimblandy** [comment] 2023-12-15 15:35
Closing as duplicate of #4731.

**Closed by jimblandy** 2023-12-15 15:35 UTC
Labels: type: bug, area: correctness
