### ISSUE TITLE
`wgpu` hangs on resize (even in example applications)

### ISSUE THREAD

**Issue by jfrimmel** [gfx-rs/wgpu#1971] opened 2021-09-15 17:40 UTC
This is an upstream report of https://github.com/sotrh/learn-wgpu/issues/230, which I found while learning the `wgpu` API.

**Description**
When I resize the window, sometimes the application hangs endlessly. I've recorded a GIF demonstrating the issue:
![learn-wgpu_tutorial2-bug](https://user-images.githubusercontent.com/31166235/133482031-7349ce09-c706-4244-bf23-59e5a38d3952.gif)
This is an example of the https://github.com/sotrh/learn-wgpu repository, but the examples in this repository are affected as well.

**Repro steps**
See the [downstream issue](https://github.com/sotrh/learn-wgpu/issues/230).

**Expected vs observed behavior**
I expected the window to resize and render properly every time. Instead the window hangs after a random amount of resizing.

**Extra materials**
See the GIF above.

**Platform**
Hardware/OS setup:
```bash
$ uname -srvmo
Linux 5.13.13-arch1-1 #1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000 x86_64 GNU/Linux
$ lspci | grep -i vga
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 615 (rev 02)
$ # X11 and KDE
```
Software versions:
- Rust 1.55.0
- winit 0.25.0
- wgpu a7c7c9f38ef7ec34a5ac4eba32ac162f33db62b2

Let me know, if there is missing information.

**Comment by kvark** [comment] 2021-09-15 17:41
@jfrimmel could you reproduce this in `wgpu` examples?

**Comment by jfrimmel** [comment] 2021-09-15 17:42
Yes, I've seen that multiple times there. I'll prepare a GIF.

**Comment by jfrimmel** [comment] 2021-09-15 17:52
Here with the `boids` example of this repository:
![wgpu-resize-hang3](https://user-images.githubusercontent.com/31166235/133484320-cf439512-7538-4081-b5c2-558e89ea3e43.gif)

**Comment by kvark** [comment] 2021-09-15 17:54
Interesting. So after a while you just lose the ability to resize...
Could you check Ash examples on your machine?

**Comment by jfrimmel** [comment] 2021-09-16 07:41
They don't work, although the reason is entirely different 😉 
```
$ git show -s
commit 1b4c82e1d61fa199e135a075bc9f456e6ff47858 (HEAD, tag: 0.33.3)
Author: Marijn Suijten <marijn@traverseresearch.nl>
Date:   Wed Sep 8 11:31:45 2021 +0200

    Release ash 0.33.3 with Vulkan-Headers 1.2.191
$ cargo run --example winit
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/examples/winit`
surface: 0x55da5fa9de20
thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid', /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/mem/mod.rs:663:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I cannot get it to run, presumably because of an old `winit` version used. I'll try to update the `winit` version to get the example working...

**Comment by kvark** [comment] 2021-09-16 15:03
Wow, that's an interesting error!

**Comment by Arevjensen** [comment] 2021-11-13 09:00
I ran into the same error and tried to figure out if I could make some changes to get it working.
As far as I can tell the error happens in Event::RedrawRequested when state.render() returns Err(wgpu::SurfaceError::Outdated)
I'm just following along a tutorial so I have no idea what I'm doing yet, but first I tried
`Err(wgpu::SurfaceError::Outdated) => state.resize(state.size)` 
This did nothing
The error description is "The underlying surface has changed, and therefore the swap chain must be updated", but as far as i can tell the swapchain is deprecated for surface. I'm not sure how to just update the surface so I ended up making a new state  when this error returned from the render function
` Err(wgpu::SurfaceError::Outdated) => {
                    state = pollster::block_on(State::new(&window))
                }`
This works as in it doesn't crash, but I'm not 100% sure of the consequences or why it fixes it

**Comment by sotrh** [comment] 2021-11-14 18:26
@Arevjensen what OS are you on?

**Comment by Arevjensen** [comment] 2021-11-14 19:48
@sotrh 
Ubuntu 21.04 hirsute 5.11.0-40
i3 8145u
intel UHD graphics 620

**Comment by sotrh** [comment] 2021-11-15 17:21
Ok, so it doesn't seem like it's an issue with a particular linux distro. Are you using wayland? I'm using X and I haven't been able to recreate this issue.

My guess for why recreating `State` works is because it creates a new `Surface` rather than reconfiguring the old one. It seems the surface is getting desynced from the window. Recreating the surface would fix that as the new surface would be setup properly.

**Comment by Arevjensen** [comment] 2021-11-17 20:22
Display: x11 server: X.Org 1.20.11 compositor: kwin_x11 driver: loaded: modesetting

**Comment by cwfitzgerald** [comment] 2023-10-14 03:32
Closing as out of date and pre-hal

**Closed by cwfitzgerald** 2023-10-14 03:32 UTC
Labels: type: bug, api: gles, api: vulkan, area: wsi
