### ISSUE TITLE
Operator precedence bug

### ISSUE THREAD

**Issue by pwouik** [gfx-rs/wgpu#6056] opened 2024-07-28 18:32 UTC
**Description**

```
[2024-07-28T18:26:29Z ERROR naga::valid::expression] Left: Binary { op: ExclusiveOr, left: [33], right: [34] } of type Scalar(Scalar { kind: Uint, width: 4 })
[2024-07-28T18:26:29Z ERROR naga::valid::expression] Right: Literal(Bool(false)) of type Scalar(Scalar { kind: Bool, width: 1 })
error: 
   ┌─ traversal.wgsl:16:8
   │
16 │     if((workgroup_id.x ^ workgroup_id.y) & 1u == 0u) {
   │        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ naga::Expression [37]

Entry point main at Compute is invalid: 
        Expression [37] is invalid
        Operation And can't work with [35] and [36]
```

== take precedence over bitwise &
seems like it is not following the spec, and doesn't make sense anyway

**Platform**
wgpu 22.0.0

**Comment by teoxoy** [comment] 2024-07-29 10:00
Closing as duplicate of https://github.com/gfx-rs/wgpu/issues/4536.

**Closed as not planned by teoxoy** 2024-07-29 10:00 UTC
