### ISSUE TITLE
[wgsl-in] Immutable array cannot be accessed with mutable index

### ISSUE THREAD

**Issue by HactarCE** [gfx-rs/wgpu#4920] opened 2023-12-22 00:35 UTC
**Description**
An array assigned to an immutable variable cannot be accessed using an index from a mutable binding.

**Repro steps**
Compile this code in a WGSL shader:
```
fn f() {
    let a = array<f32, 10>();

    let i = 0;
    let x = a[i]; // compiles fine

    var j = 0;
    let y = a[j]; // error: The expression may only be indexed by a constant
}
```

**Expected vs observed behavior**
I expect `f` to compile with no issue, but instead I get an error when attempting to access `a[j]`.

**Platform**
- OS: macOS Sonoma 14.2
- `wgpu`: latest from `trunk`

**Comment by nical** [comment] 2024-01-03 10:35
Duplicate of https://github.com/gfx-rs/wgpu/issues/4337

**Closed as not planned** 2024-01-03 15:16 UTC
Labels: type: bug, naga, area: naga front-end, lang: WGSL
