### ISSUE TITLE
Panic when taking the address of a struct within a struct

### ISSUE THREAD

**Issue by pcwalton** [gfx-rs/wgpu#5593] opened 2024-04-24 00:42 UTC
**Description**

This panics:

```wgsl
struct S0 {
    a: f32,
}

struct S1 {
    s0: S0,
    b: f32,
}

fn g(s0: ptr<function, S0>) {}

fn f(s1: ptr<function, S1>) {
    g(&(*s1).s0);
}

@compute
@workgroup_size(64, 1, 1)
fn main() {
    var s1: S1;
    s1.s0.a = 0.0;
    s1.b = 0.0;
    f(&s1);
}
```

`internal error: entered unreachable code: Expression [2] is not cached!`

**Repro steps**

```bash
$ target\debug\naga.exe bug.wgsl bug.spv
thread 'main' panicked at naga\src\back\spv\block.rs:2254:56:
internal error: entered unreachable code: Expression [2] is not cached!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Platform**
Windows 11, x86-64

**Comment by teoxoy** [comment] 2024-04-24 08:44
This looks like a duplicate of https://github.com/gfx-rs/wgpu/issues/4540.

**Closed as not planned by teoxoy** 2024-04-24 08:44 UTC
Labels: type: bug, lang: WGSL
