### ISSUE TITLE
get_bind_group_layout fails when layout is auto

### ISSUE THREAD

**Issue by sagudev** [gfx-rs/wgpu#6095] opened 2024-08-09 12:28 UTC
**Description**
When layout is not explicitly provided when creating pipeline, `get_bind_group_layout` fails with `Error reflecting bind group 0: Invalid group index 0`, but explicitly providing it makes it work.

**Repro steps**
Relevant CTS test that fails in firefox (and servo): [webgpu:api,validation,getBindGroupLayout:index_range,auto_layout:*](https://gpuweb.github.io/cts/standalone/?debug=1&runnow=1&q=webgpu:api,validation,getBindGroupLayout:index_range,auto_layout:*
)

I also extracted relevant failing CTS subtest in rust/wgpu repro: https://github.com/sagudev/wgpu-problem/tree/get-auto-bind-group-layout (also contains explicit code that makes it work using `explicit` feature).

**Platform**
Happens on current trunk.

**Comment by sagudev** [comment] 2024-08-09 12:41
This happens on both compute/render pipeline.

**Comment by Wumpf** [comment] 2024-09-15 18:14
Duplicate of
* https://github.com/gfx-rs/wgpu/issues/4167

**Comment by sagudev** [comment] 2024-09-20 12:50
I tested repro with https://github.com/gfx-rs/wgpu/pull/6280 and while it does not panic it still raises validation error (per CTS it should return appropriate bind group), so please reopen the issue.

**Comment by sagudev** [comment] 2024-09-20 15:29
The problem is that `usage = 0`:
https://github.com/gfx-rs/wgpu/blob/9f85f8aeea6c43c1a412bafc8fbcfb43aad0dd20/wgpu-core/src/validation.rs#L897-L900
for compute pipeline with:
```wgsl
@group(0) @binding(0) var<uniform> binding: f32;

@compute @workgroup_size(1) fn main(
  @builtin(global_invocation_id) id: vec3<u32>
) {
    _ = binding;
}
```

**Comment by sagudev** [comment] 2024-09-21 06:12
More specifically the problem is that naga eliminates phony assigement, converting wgsl from above to wgsl returns:
```wgsl
@group(0) @binding(0) 
var<uniform> binding: f32;

@compute @workgroup_size(1, 1, 1)
fn main(@builtin(global_invocation_id) id: vec3<u32>) {
}
```

**Comment by sagudev** [comment] 2024-09-21 06:42
this is regression naga-cli v0.12.3` -> `naga-cli v0.13.0

**Comment by sagudev** [comment] 2024-09-21 06:44
I think it's https://github.com/gfx-rs/naga/pull/2378, but also we remove expressions on compacting ...

**Closed as completed** 2024-09-27 21:52 UTC
Labels: type: bug
