### ISSUE TITLE
WGSL mat3x2 type translation to GLSL not working

### ISSUE THREAD

**Issue by samuelselleck** [gfx-rs/wgpu#4611] opened 2023-10-30 05:21 UTC
**Description**
Using the mat3x2 type in a WGSL shader struct loaded as a uniform gives what I think is a misalignment error when running on the WebGL backend:
`[.WebGL-0x134005a4d00] GL_INVALID_OPERATION: It is undefined behaviour to use a uniform buffer that is too small.`

```wgsl
struct Transform {
    transform: mat3x2<f32>,
    _pad1: u32,
    _pad2: u32,
}

struct Transforms {
    transforms: array<Transform, 64>,
}

@group(0) @binding(0) var<uniform> clipping: Transforms;

// used clipping variable in fragment shader.
```

When replacing `transform` with 6 individual f32 fields everything works on both Metal and WebGL.

**Expected vs observed behavior**
I expect valid WGSL code that runs on Metal to get translated to valid GLSL as well.

**Platform**
MacOS, wgpu v0.18.

**Comment by cwfitzgerald** [comment] 2023-10-30 06:00
Thanks for filing! This is a dupe of

#4371

**Closed as not planned by cwfitzgerald** 2023-10-30 06:00 UTC

**Comment by samuelselleck** [comment] 2023-10-30 07:01
Sorry about that, thanks for pointing me in the right direction!

**Comment by cwfitzgerald** [comment] 2023-10-30 14:49
No worries! Would much rather have duplicates than miss issues!
