### ISSUE TITLE
(WebGL2) Validator says I can't use SSBO, but disabling the validator makes the shader work

### ISSUE THREAD

**Issue by Patryk27** [gfx-rs/wgpu#3200] opened 2022-11-10 19:00 UTC
Trying to use an SSBO in a fragment shader fails with:
```
wgpu error: Validation Error

Caused by:
    In Device::create_bind_group_layout
      note: label = `geometry_bind_group_layout`
    too many bindings of type StorageBuffers in stage FRAGMENT, limit is 0, count was 1
```
_(checked on Linux / Chromium 106.0.5249.119 & Firefox 106.0.1 / Mesa Intel(R) UHD Graphics 630 (CFL GT2); a friend has also confirmed the same behavior on Edge)_

Now, on a surface, the validator is kinda-sorta right, because not only do my browsers report themselves as `WebGL GLSL ES 3.00`, force-disabling the check at:
https://github.com/gfx-rs/wgpu/blob/9f82504d8a3b6e234599b19cc35c299bcec8b138/wgpu-hal/src/gles/adapter.rs#L209
... but - even with that check commented out - `gl.get_parameter_i32(glow::MAX_FRAGMENT_SHADER_STORAGE_BLOCKS)` returns 0.

The issue is that, well, disabling the validation makes the shader work.

That is, doing (patch based on v0.13):
```diff
diff --git a/wgpu-core/src/binding_model.rs b/wgpu-core/src/binding_model.rs
index 458723a3..8ab1f818 100644
--- a/wgpu-core/src/binding_model.rs
+++ b/wgpu-core/src/binding_model.rs
@@ -360,18 +360,18 @@ impl BindingTypeMaxCountValidator {
             limits.max_sampled_textures_per_shader_stage,
             BindingTypeMaxCountErrorKind::SampledTextures,
         )?;
-        self.storage_buffers.validate(
-            limits.max_storage_buffers_per_shader_stage,
-            BindingTypeMaxCountErrorKind::StorageBuffers,
-        )?;
+        // self.storage_buffers.validate(
+        //     limits.max_storage_buffers_per_shader_stage,
+        //     BindingTypeMaxCountErrorKind::StorageBuffers,
+        // )?;
         self.samplers.validate(
             limits.max_samplers_per_shader_stage,
             BindingTypeMaxCountErrorKind::Samplers,
         )?;
-        self.storage_buffers.validate(
-            limits.max_storage_buffers_per_shader_stage,
-            BindingTypeMaxCountErrorKind::StorageBuffers,
-        )?;
+        // self.storage_buffers.validate(
+        //     limits.max_storage_buffers_per_shader_stage,
+        //     BindingTypeMaxCountErrorKind::StorageBuffers,
+        // )?;
         self.storage_textures.validate(
             limits.max_storage_textures_per_shader_stage,
             BindingTypeMaxCountErrorKind::StorageTextures,
diff --git a/wgpu-core/src/device/mod.rs b/wgpu-core/src/device/mod.rs
index cdf5b197..8f32cd79 100644
--- a/wgpu-core/src/device/mod.rs
+++ b/wgpu-core/src/device/mod.rs
@@ -1649,11 +1649,11 @@ impl<A: HalApi> Device<A> {
             Some(size) => {
                 let end = bb.offset + size.get();
                 if end > buffer.size {
-                    return Err(Error::BindingRangeTooLarge {
-                        buffer: bb.buffer_id,
-                        range: bb.offset..end,
-                        size: buffer.size,
-                    });
+                    // return Err(Error::BindingRangeTooLarge {
+                    //     buffer: bb.buffer_id,
+                    //     range: bb.offset..end,
+                    //     size: buffer.size,
+                    // });
                 }
                 (size.get(), end)
             }
@@ -1661,11 +1661,11 @@ impl<A: HalApi> Device<A> {
         };
 
         if bind_size > range_limit as u64 {
-            return Err(Error::BufferRangeTooLarge {
-                binding,
-                given: bind_size as u32,
-                limit: range_limit,
-            });
+            // return Err(Error::BufferRangeTooLarge {
+            //     binding,
+            //     given: bind_size as u32,
+            //     limit: range_limit,
+            // });
         }
 
         // Record binding info for validating dynamic offsets
```
... and re-running the code in web browser just-works :tm:

I _think_ the issue boils down to ANGLE (which is used by both Firefox and Chrome) hardcoding the number of available storage blocks to zero:
https://github.com/google/angle/blob/7f42f858e2b232338bd520fe3527e1d07cebdb1a/src/libANGLE/Caps.cpp#L1102
(a brief look at the code suggests that this value is actually properly filled out only for the d3d11 renderer)

And so, having all that in mind, maybe it would be better to disable the validation? 😅 

To be fair, this feels like a bug in Firefox and/or Chrome and/or ANGLE, but eventually it's the validation in wgpu that hurts me in this case directly, so - just pitchin' - maybe it would be better to hard-code those few limits to `Limits::downlevel_defaults()`, at least for the time being?

(due diligence: I'm just starting playing with shaders and whatnot, so I might be totally off here - I'm just following my hunch)

**Comment by cwfitzgerald** [comment] 2022-11-10 21:34
Do you have a repro case for this? If ff/chrome are letting through SSBOs in shaders on WebGL2 that's 100% a bug on their end as there shouldn't be any allowed. In addition, the call to `glBindBufferRange` when you bind the bind group should fail on WebGL2 as `GL_SHADER_STORAGE_BUFFER` isn't a thing there.

**Comment by Patryk27** [comment] 2022-11-10 21:40
Ah, I see!

So the thing is that WebGL2 is supposed to be capped to GLSL ES 3.0's functionalities and that's why even though my iGPU supports the newer standard, SBBOs & other newer features should get forbidden, right?

> Do you have a repro case for this?

I'm writing a game for GitHub's Game Off, but I guess that's too big for a repro 😅 I'll try preparing something minimal tomorrow.

**Comment by cwfitzgerald** [comment] 2022-11-10 21:43
> So the thing is that WebGL2 is supposed to be capped to GLSL ES 3.0's functionalities and that's why even though my iGPU supports the newer standard, SBBOs & other newer features should get forbidden, right?

Correct

Does binding a bind group to that shader and drawing actually work?

**Comment by Patryk27** [comment] 2022-11-10 21:44
Yeps, everything works & looks like in an equivalent Linux program 🙂

**Comment by cwfitzgerald** [comment] 2022-11-10 21:44
Big spook

**Comment by cwfitzgerald** [comment] 2022-11-10 21:45
Hey at least our validation catches the issue before it turns into (essentially) UB 😆

**Comment by teoxoy** [comment] 2022-12-05 16:20
I think we can close this since it's expected behavior.

**Closed by teoxoy** 2022-12-05 16:20 UTC
