### ISSUE TITLE
Android emulator surface issue

### ISSUE THREAD

**Issue by dm67x** [gfx-rs/wgpu#3972] opened 2023-07-24 19:07 UTC
Hi,

I try to run wgpu program on Android using an emulator but it didn't work.

![image](https://github.com/gfx-rs/wgpu/assets/1593334/1fd4da99-8598-4255-a289-a0afe236d935)

Btw, it's working on a real device.
Did I miss something or is it normal?

Thanks!

**Comment by teoxoy** [comment] 2023-08-01 13:03
Could you share the whole log as text? It would also make it easier for others to find the issue.

**Comment by dm67x** [comment] 2023-08-05 10:20
Of course, [logs.txt](https://github.com/gfx-rs/wgpu/files/12266817/logs.txt)

**Comment by teoxoy** [comment] 2023-08-07 13:27
The error looks similar to https://github.com/gfx-rs/wgpu/issues/2101 & https://github.com/gfx-rs/wgpu/issues/2384.

Could you try to run it only with the GL backend enabled (change `Backends::all()` to `Backends::GL`)?

**Comment by jinleili** [comment] 2023-08-12 09:55
Using `wgpu::Backends::all()` works fine on Android phones (OnePlus Ace Pro, Android 13) because `device_type` are all `IntegratedGpu`, and the picking order will pick the Vulkan backend:
```log
AdapterInfo { name: "Adreno (TM) 730", vendor: 20803, device: 117637122, device_type: IntegratedGpu, driver: "Qualcomm Technologies Inc. Adreno Vulkan Driver", driver_info: "Driver Build: ee4b625, I41c6f366e1, 1676536850\nDate: 02/16/23\nCompiler Version: EV031.36.08.19\nDriver Branch: \n", backend: Vulkan }

AdapterInfo { name: "Adreno (TM) 730", vendor: 20803, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
```
However, in the emulator, the `device_type` for the Vulkan backend is `Cpu`, so it will only pick the GL backend:
```log
AdapterInfo { name: "SwiftShader Device (LLVM 10.0.0)", vendor: 6880, device: 49374, device_type: Cpu, driver: "?", driver_info: "?", backend: Vulkan }

AdapterInfo { name: "Android Emulator OpenGL ES Translator (Apple M1 Max)", vendor: 4203, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
```

Using `wgpu::Backends::GL` works fine on Android phones, but it throws an error in the emulator:
```log
eglMakeCurrent: 0x7ab3fc7780: ver 3 0 (tinfo 0x7b498defe0)
2023-08-12 15:09:48.677 10220-10220 wgpu::backend::direct   name.jinleili.wgpu.debug             E  Handling wgpu errors as fatal by default
2023-08-12 15:09:48.677 10220-10220 log_panics              name.jinleili.wgpu.debug             E  thread '<unnamed>' panicked at 'wgpu error: Validation Error
Caused by:
		In Device::create_render_pipeline
		Error matching ShaderStages(VERTEX) shader requirements against the pipeline 
		Shader uses 2 inter-stage components above the limit of 0

': /Users/lijinlei/Rust/forks/wgpu/wgpu/src/backend/direct.rs:3095
```

**Comment by dm67x** [comment] 2023-08-15 18:04
@teoxoy yes it's working when I changed it to the OpenGL backend.

**Comment by teoxoy** [comment] 2023-08-16 13:29
This is most likely a dupe of https://github.com/gfx-rs/wgpu/issues/2384.

> Well that sucks. Both Instance and Surface in wgpu are for all of the active backends, simlultaneously. It looks like the Vulkan surface was created here, and it's blocking EGL surface.

_from https://github.com/gfx-rs/wgpu/issues/2384#issuecomment-1011414732_

**Comment by dm67x** [comment] 2023-08-17 21:34
@teoxoy what should I do with this issue? Should I close it?

**Comment by teoxoy** [comment] 2023-08-18 09:10
I think we can close it for now.

**Closed as not planned by teoxoy** 2023-08-18 09:10 UTC
Labels: type: bug

**Comment by teoxoy** [comment] 2023-08-18 09:13
> Using `wgpu::Backends::GL` works fine on Android phones, but it throws an error in the emulator:
> 
> ```
> eglMakeCurrent: 0x7ab3fc7780: ver 3 0 (tinfo 0x7b498defe0)
> 2023-08-12 15:09:48.677 10220-10220 wgpu::backend::direct   name.jinleili.wgpu.debug             E  Handling wgpu errors as fatal by default
> 2023-08-12 15:09:48.677 10220-10220 log_panics              name.jinleili.wgpu.debug             E  thread '<unnamed>' panicked at 'wgpu error: Validation Error
> Caused by:
> 		In Device::create_render_pipeline
> 		Error matching ShaderStages(VERTEX) shader requirements against the pipeline 
> 		Shader uses 2 inter-stage components above the limit of 0
> 
> ': /Users/lijinlei/Rust/forks/wgpu/wgpu/src/backend/direct.rs:3095
> ```

@jinleili the limit being 0 in the emulator doesn't sound right. Could you open a new issue for it?
