### ISSUE TITLE
vkBindImageMemory validation error and crash

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#345] opened 2019-10-03 02:24 UTC
on wgpu 0.3.0, after updating my intel vulkan drives on linux, I'm seeing this validation error, and subsequent hang and crash:

```
VALIDATION [VUID-vkBindImageMemory-memoryOffset-01048 (0)] : vkBindImageMemory(): memoryOffset is 0x46e00 but must be an integer multiple of the VkMemoryRequirements::alignment value 0x1000, returned from a call to vkGetImageMemoryRequirements with image. The Vulkan spec states: memoryOffset must be an integer multiple of the alignment member of the VkMemoryRequirements structure returned from a call to vkGetImageMemoryRequirements with image (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkBindImageMemory-memoryOffset-01048)
object info: (type: IMAGE, hndl: 2903)
```

And just before the crash:
```
INTEL-MESA: error: ../mesa-19.1.7/src/intel/vulkan/anv_device.c:2568: GPU hung on one of our command buffers (VK_ERROR_DEVICE_LOST)
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Ok(())`,
 right: `Err(ERROR_DEVICE_LOST)`', /home/m4b/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.3.3/src/lib.rs:1174:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Err(DeviceLost(DeviceLost))`,
 right: `Ok(true)`: GPU got stuck :(', /home/m4b/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.3.3/src/device.rs:204:13
```

Effectively, I have a shader which takes an image, binds a texture, then copies some stuff to a storage buffer.

If i re-run the entire shader pass, e.g., re-bind everything given the identical image `&[u8]`, it crashes like above. So it's just running the shader again with same input; my guess is gpu memory is reallocated, and the new memory allocation doesn't have the proper alignment?

**Comment by kvark** [comment] 2019-10-03 13:53
Looks like a duplicate of #323
@omni-viral is the fix published?

**Comment by omni-viral** [comment] 2019-10-03 18:01
@kvark No, but it we have planned to backport it to current minor version. Everything stuck with me being PC-less for few weeks :(

**Comment by kvark** [comment] 2019-10-03 18:03
dear lord, get a man some PC from those Amethyst grants!

**Comment by omni-viral** [comment] 2019-10-03 20:50
Don't want to go far in offtopic here, but it's not easy due to locations.

**Comment by m4b** [comment] 2019-10-03 21:17
I’m ok without a back port as long as it’s in wgpu 0.4 essentially

**Comment by cwfitzgerald** [comment] 2020-12-01 18:01
I believe this should be fixed.

**Closed by cwfitzgerald** 2020-12-01 18:01 UTC
