### ISSUE TITLE
flickering when pipeline reused

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#225] opened 2019-06-12 03:14 UTC
I don't have an immediate repro (and I can't seem to repro in a straightforward manner on cube example) but I have a function like this:

```rust
    pub fn draw(&self, bind_group: &wgpu::BindGroup, rpass: &mut wgpu::RenderPass) {
        rpass.set_pipeline(&self.pipeline);
        rpass.set_bind_group(0, bind_group, &[]);
        rpass.set_vertex_buffers(&[(&self.buf, 0)]);
        rpass.draw(0..(self.buf.len()) as u32, 0..1);

        if self.strips_buf.len() != 0 {
            // this is required because of a bug in wgpu which causes flickering unless we reset teh pipeline and bind group
            rpass.set_pipeline(&self.pipeline); // <------ must re-set this otherwise flickers
            rpass.set_bind_group(0, bind_group, &[]);
            rpass.set_vertex_buffers(&[(&self.strips_buf, 0)]);
            rpass.draw(0..(self.strips_buf.len()) as u32, 0..1);
        }
    }
```

E.g., I have to re-`set_pipeline` (but not the bind group), for the same pipeline (and bindgroup), otherwise i see flickering on the resultant triangle from the vertices in `self.strips_buf`.

I don't immediately know why this would happen, and I use the above workaround, but @kvark suggested I should file anyway so it's here and that it's probably a bug in wgpu.

I don't have any validation errors, etc., this is on vulkan backend, archlinux os, intel integrated gpu.

**Comment by kvark** [comment] 2019-06-14 14:11
Are you seeing validation errors in general on this setup? Would you see them if something was clearly incorrect?

**Comment by m4b** [comment] 2019-06-14 15:18
Yes I always see validation errors if something is wrong, eg wrong flags, etc. only time I haven’t is previous issue where I passed too many elements to a draw call, but that is now fixed in master.

There have been times where I think a shader was writing/reading to points in a buffer, and I did not receive any crashes or warnings (on both metal and vulkan backends) but I don’t know if validation errors can catch that gpu side issue ?

**Comment by kvark** [comment] 2019-06-14 15:21
Our validation is still WIP, so it can easily miss some cases, especially if they are related to shader reflection/sanitation (which we haven't gotten hooked up yet).

**Comment by m4b** [comment] 2019-06-14 15:49
Ok I’ll double check but I don’t think I’m reading or writing any invalid memory anymore, and as far as I can see there aren’t any major issues remaining.

**Comment by aloucks** [comment] 2019-06-15 03:45
Do you have other pipelines or bind groups? Could this be a case of the bind group being "disturbed" by another bind?

https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#descriptorsets-compatibility

> When binding a descriptor set (see Descriptor Set Binding) to set number N, if the previously bound descriptor sets for sets zero through N-1 were all bound using compatible pipeline layouts, then performing this binding does not disturb any of the lower numbered sets. If, additionally, the previous bound descriptor set for set N was bound using a pipeline layout compatible for set N, then the bindings in sets numbered greater than N are also not disturbed.

**Comment by m4b** [comment] 2019-06-15 04:42
Hmm yes I have other pipelines and bind groups. But I think the cube demo does too ? If not would be interesting to see if having multiple pipelines and bind groups and the reusing one could cause this issue

**Comment by aloucks** [comment] 2019-06-15 17:40
The bindings are only disturbed if the pipelines are considered incompatible.

**Comment by m4b** [comment] 2019-06-15 18:02
Yea I was rereading that. But in my example above why would that cause flickering? I rebind the exact same pipeline just to avoid flickering when I change the bound vertex buffer, which also has the same layout as the previous vertex buffer.

**Comment by dragly** [comment] 2019-07-30 08:15
This is definitely related to https://github.com/gfx-rs/wgpu-rs/issues/49

@m4b I tried your workaround of re-setting the pipeline before the second draw call and that stops the flickering.

In my modified cube example (https://github.com/dragly/wgpu-rs/commit/cc36db229b416390892457c0bd0d3bb430dbec2a), the following conditions need to be met to reproduce flickering:

- There must be both a compute pass and a render pass. The compute pass can be no-op.
- The first draw call must have some load. In my case, drawing 32x32x32 instances does the trick.
- The pipeline needs to be reused (as is pointed out in this issue already).

Let me know if there is anything I can do to help debug this issue.

**Comment by m4b** [comment] 2019-07-30 15:56
Awesome thanks for checking ! Great detail too, thanks!

**Comment by dragly** [comment] 2019-07-31 14:31
As mentioned in https://github.com/gfx-rs/wgpu-rs/issues/49, I filed a [bug report](https://bugs.freedesktop.org/show_bug.cgi?id=111267) to Mesa and it was immediately reported as a [duplicate](https://bugs.freedesktop.org/show_bug.cgi?id=109630) of a similar issue in vkQuake. Seems like this could be a graphics driver bug.

**Comment by dragly** [comment] 2019-08-01 12:34
@m4b a patch that solved the issue for me was just posted here, in case you want to try it out and see if it also fixes your issue: https://gitlab.freedesktop.org/mesa/mesa/merge_requests/1526

**Comment by kvark** [comment] 2019-08-31 04:58
I wonder if this is related to the problems #319 is fixing. I know that Mesa patch saves the day, but re-setting the pipeline could also make an effect on our binding code.

**Comment by dragly** [comment] 2019-09-24 13:31
Rebased on top of the latest version of wgpu-rs and the problem persists. Seems like the Mesa patch is still necessary.

**Comment by kvark** [comment] 2021-05-02 05:08
@dragly could you check again?

**Comment by dragly** [comment] 2021-05-14 10:29
@kvark unfortunately, after change of jobs I do not have the same hardware available anymore and will not be able to check if the issue is fixed. Sorry about that.

**Comment by kvark** [comment] 2021-05-14 18:45
@m4b do you happen to have a test case to check this?

**Comment by m4b** [comment] 2021-05-16 01:37
So:

1. i don't see any flickering for a while
2. i just checked, and i don't have the code that originally caused it, but i do something similar:

```rust
        rpass.set_pipeline(&pipeline);
        rpass.set_bind_group(0, bind_group, &[]);
        if dynamic {
            if let Some(buf) = &self.dynamic {
                rpass.set_vertex_buffer(0, self.vertex_buffer.slice(..));
                rpass.set_vertex_buffer(1, buf.slice(..));
                rpass.draw(0..self.vertex_buffer.len() as u32, 0..buf.len() as u32);
            }
        }
        if statik {
            if let Some(buf) = &self.statik {
                rpass.set_vertex_buffer(0, self.vertex_buffer.slice(..));
                rpass.set_vertex_buffer(1, buf.slice(..));
                rpass.draw(0..self.vertex_buffer.len() as u32, 0..buf.len() as u32);
            }
        }
```

which i believe should have exhibited this flickering issue? (my original example had to reset the same pipeline when i switched the vertex buffer iirc)

So i'm not sure, seems gone now to me? anyway, at the very least, it seems ok to reuse pipelines in same rpass call, at least in the way above, but i do recall a repro of this being hard as well.

**Comment by kvark** [comment] 2021-05-16 03:45
Thank you! Let's close the issue and be ready to re-open it if it shows up again.

**Closed by kvark** 2021-05-16 03:45 UTC
Labels: external: driver-bug, type: bug
