### ISSUE TITLE
Interop with underlying graphics API

### ISSUE THREAD

**Issue by dylanede** [gfx-rs/wgpu#965] opened 2020-10-07 11:56 UTC
Is there a user-facing mechanism for accessing the native API handles underlying given wgpu objects so that interop can be performed? If not, are there any plans for such an escape hatch? Specifically I'm interested in using external memory objects from Vulkan.

**Comment by kvark** [comment] 2020-10-07 14:25
There isn't currently any mechanism to do so. I assume that you are talking about native-only support, outside of WebGPU proper. In this case, first step would be implementing the "external memory objects" in gfx-hal. Then we'd be able to hook it up here.

**Comment by AdrianEddy** [comment] 2021-12-17 09:57
Is there any progress on this issue? 

My use case is the following: I want to do video processing on the GPU, I have the textures from OpenGL, Metal, DirectX and Vulkan and I would like to pass them to wgpu, process the pixels and draw it back, all without going through CPU memory. 

I use Qt and it supports different graphic APIs via the [QRhi](https://doc.qt.io/qt-6/topics-graphics.html), so it'd be nice to be able to support the same graphic APIs to do the processing directly, and for that I need to be able to feed the `wgpu` shader with an external texture and render target from the underlying graphic api.

**Comment by kvark** [comment] 2021-12-17 14:41
There is quite a bit of progress overall, although more may be needed.
First, we have our own `wgpu-hal` now, not using `gfx-hal` any more. So doing any plumbing work becomes much easier - everything is in this repo.
Second, we have `create_texture_from_hal` - #1609

**Comment by coderedart** [comment] 2022-04-19 15:43
I have a use case where i would like to use a wgpu texture, so that i can use it in opengl.
I need window level transparency and wgpu does not support it at the moment. https://github.com/gfx-rs/wgpu/issues/687 
even if it exposes the composite modes, nvidia drivers (vulkan) only export opaque mode, but don't care about it.instead they just allow transparency. since its a very niche issue, i'm afraid driver devs won't take it seriously and prioritize it or any bugs that follow after exposing composite modes.

meanwhile, opengl works great already for transparency. and mpv can use opengl context to render its video directly into my app. there is no mature video player using vk/wgpu afaik like mpv.

but ofcourse, all the unsafe and thread-safety :( is horrible to deal with in rust. 

my plan is to 
1. create an opengl window
2. create wgpu (vk ) texture. 
3. import that texture into opengl.
4. render all my stuff in wgpu using its safe and rusty api into the exported texture.
5. put it on to gl framebuffer. use mpv to render video if needed. swapBuffers in opengl.
6. repeat 4 and 5.

I can then release the above opengl-wgpu hybrid version, and a normal full wgpu version. those who have issues with vk drivers can use hybrid version.

this way, i can stay with wgpu 90% of the time and only use opengl in specific / backwards compatible places, waiting to deprecate it as issues are fixed.

**Comment by cwfitzgerald** [comment] 2022-04-19 16:39
Note that wgpu does have an OpenGL backend, so you shouldn't need to share between native apis at all, you can just run us from that same context

**Comment by coderedart** [comment] 2022-04-19 17:00
that's nice. but i need vulkan backend. 
1. angle is only Best Effort Support according to README :(
2. rend3 only lists vulkan / dx / metal as its supported platforms( with vulkan for gpu-driven profile). :(
3.I also need some features like multi draw indirect count or non-uniform indexing which are only available on vulkan :(

**Comment by coderedart** [comment] 2022-04-19 17:02
https://github.com/gfx-rs/wgpu/issues/1460 might be a duplicate of this

**Comment by cwfitzgerald** [comment] 2023-12-27 07:47
Closing in favor of #4067 which is a concrete plan

**Closed by cwfitzgerald** 2023-12-27 07:47 UTC
Labels: type: question, area: api
