### ISSUE TITLE
VertexFormat::size() is not const.

### ISSUE THREAD

**Issue by Hscowef** [gfx-rs/wgpu#930] opened 2020-09-14 23:56 UTC
**Description**
The `wgpu-types::VertexFormat::size()` function is not marked as `const` which may be limiting in certain situations for example the [wgpu::vertex_attr_array](https://docs.rs/wgpu/0.6.0/wgpu/macro.vertex_attr_array.html) macro can't be used in const contex when there are mutliple "arguments" .

**Repro steps**
This is literally a one word fix which consist of remplacing [this function signature](https://github.com/gfx-rs/wgpu/blob/master/wgpu-types/src/lib.rs#L1146) by `pub const fn size(&self) -> u64`.

**Comment by kvark** [comment] 2020-09-15 00:13
Dupe of #836

**Closed by kvark** 2020-09-15 00:13 UTC
