### ISSUE TITLE
vkCmdPipelineBarrier(): Image barrier 0x0x560107cfb730 references image 0x65 of formatVK_FORMAT_D24_UNORM_S8_UINT that must have the depth and stencil aspects set, but its aspectMask is 0x4.

### ISSUE THREAD

**Issue by Yatekii** [gfx-rs/wgpu#376] opened 2019-11-07 23:30 UTC
I don't know where exactly this comes from but it's only since v 0.4 :)

VALIDATION [VUID-VkImageMemoryBarrier-image-01207 (0)] : vkCmdPipelineBarrier(): Image barrier 0x0x560107cfb730 references image 0x65 of formatVK_FORMAT_D24_UNORM_S8_UINT that must have the depth and stencil aspects set, but its aspectMask is 0x4. The Vulkan spec states: If image has adepth/stencil format with both depth and stencil components, then the aspectMask member of subresourceRangemust include both VK_IMAGE_ASPECT_DEPTH_BIT and VK_IMAGE_ASPECT_STENCIL_BIT (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageMemoryBarrier-image-01207)
object info: (type: IMAGE, hndl: 101)

Best,
Yatekii

**Comment by kvark** [comment] 2019-11-08 04:57
I just reviewed all our use of the usages and found out that really we aren't affected by `separateDepthStencilLayouts` and we are in a very good position to support it in the future (phew!). The bug is much simpler, fix is coming.

**Comment by kvark** [comment] 2019-11-11 04:54
I reproduced the case locally on `sailor` master and figured out what's missing in #378 . We are making transitions of depth and stencil to the same states, but we are still registering those separately... This is quite annoying and unfortunate, since it isn't going to break anything. We have two ways to proceed, neither is simple:
  1. force coalescing of the barriers on our side. This is something I'd like *not* to do because the drivers likely do something like that anyway, and we don't want to do the extra work here, especially if it's only to silence a particular validation error.
  2. implement support for merged depth-stencil as a first-class citizen
  3. implement state tracking in such a way that the aspects are only ever separated when needed (instead of always tracking them separate to begin with).

Practically, (2) would mean to have something like this:
```rust
enum DepthStencilState {
  Merged(PlaneStates),
  Separate { depth: PlaneStates, stencil: PlaneStates },
}
```

This enum would have to be matched in all the tracking methods, but it's not the end of the world.

**Closed** 2019-11-19 13:59 UTC
Labels: bug

**Comment by kvark** [comment] 2019-11-19 16:12
I tested `sailor` on https://github.com/gfx-rs/wgpu-rs/pull/122 that includes #378 and verified that the validation errors are gone.
