### ISSUE TITLE
`wgpu error: Validation Error` in `Device::create_render_pipeline`

### ISSUE THREAD

**Issue by KAIYOHUGO** [gfx-rs/wgpu#4012] opened 2023-08-07 06:11 UTC
**Description**

It throw error when running bevy 3D scene example.

**Repro steps**

Bind /tmp/X11.unix in docker, and run bevy 3D scene example in docker.

**Expected vs observed behavior**

Its throw error, but X11 example app is fine (xeyes, xclock)

```
2023-08-07T05:47:10.716767Z  WARN bevy_pbr::ssao: ScreenSpaceAmbientOcclusionPlugin not loaded. GPU lacks support: TextureFormat::R16Float does not support TextureUsages::STORAGE_BINDING.
2023-08-07T05:47:12.367727Z ERROR wgpu_hal::gles::egl: GLES: [API/Error] ID 1 : GL_INVALID_ENUM in glTexStorage2DMultisample(target=GL_TEXTURE_2D)    
2023-08-07T05:47:12.368684Z ERROR wgpu_hal::gles::egl: GLES: [API/Error] ID 1 : GL_INVALID_ENUM in glTexStorage2DMultisample(target=GL_TEXTURE_2D)    
2023-08-07T05:47:14.904821Z ERROR wgpu::backend::direct: Shader translation error for stage ShaderStages(FRAGMENT): gsamplerCubeArrayShadow isn't supported in textureGrad, textureLod or texture with bias    
2023-08-07T05:47:14.904979Z ERROR wgpu::backend::direct: Please report it to https://github.com/gfx-rs/naga    
2023-08-07T05:47:14.905166Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (0)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    Internal error in ShaderStages(FRAGMENT) shader: gsamplerCubeArrayShadow isn't supported in textureGrad, textureLod or texture with bias

', /config/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
thread 'Compute Task Pool (1)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /config/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.11.0/src/pipelined_rendering.rs:135:45
```

**Extra materials**

Install X11 in docker instead of bind it from host machine don't cause error.

I follow the step in [this Article](https://medium.com/@pigiuz/hw-accelerated-gui-apps-on-docker-7fd424fe813e)

**Platform**

Ubuntu 22.04 in Docker & Host Machine

**Comment by teoxoy** [comment] 2023-08-07 12:53
Closing as duplicate of https://github.com/gfx-rs/wgpu/issues/4455, which is a shortcoming of the GLSL backend.

**Closed as not planned by teoxoy** 2023-08-07 12:53 UTC
