### ISSUE TITLE
Unexpected override-expression for workgroup_size

### ISSUE THREAD

**Issue by KeKsBoTer** [gfx-rs/wgpu#5907] opened 2024-07-04 13:20 UTC
**Description**
When setting the workgroup size with an override-expression naga reports an error:
```
Could not parse WGSL:
error: Unexpected override-expression
  ┌─ test.wgsl:3:26
  │
3 │ @compute @workgroup_size(block_width)
  │                          ^^^^^^^^^^^ see msg


```

**Repro steps**
1. Create a file with this minimal example (taken from [the specs](https://www.w3.org/TR/WGSL/#entry-point-attributes)):
```wgsl
// Using an pipeline-overridable constant.
@id(42) override block_width = 12u;
@compute @workgroup_size(block_width)
fn shuffler() { }
```
2. Validate the shader with naga 0.20.0

**Expected vs observed behavior**
Naga validates shader without error.

**Comment by teoxoy** [comment] 2024-07-05 08:37
Closing as duplicate of https://github.com/gfx-rs/wgpu/issues/4450.

**Closed as not planned by teoxoy** 2024-07-05 08:37 UTC
