### ISSUE TITLE
Compute examples not supported in Firefox Nightly

### ISSUE THREAD

**Issue by munrocket** [gfx-rs/wgpu#4176] opened 2023-09-26 17:42 UTC
**Description**
Firefox Nightly stopped to give device, I am tried to run it on MacOS Macbook Air with Intel video card.

**Repro steps**
Open www.compute.toys or official example https://wgpu.rs/examples-gpu/?example=hello-compute in Firefox Nightly

**Expected vs observed behavior**
Should work, as it was in previous versions.

**Extra materials**
<details>
<summary>compute.toys error on Mac</summary>
panicked at 'called Option::unwrap() on a None value', examples/hello-compute/src/main.rs:19:45<br/>
<br/>
Stack:<br/>
<br/>
<pre>
__wbg_get_imports/imports.wbg.__wbg_new_abda76e883ba8a5f@https://wgpu.rs/examples-gpu/wasm/hello-compute.js:279:21
console_error_panic_hook::hook::h3ec31c7bbb959651@https://wgpu.rs/examples-gpu/wasm/hello-compute_bg.wasm:wasm-function[242]:0x151b0
core::ops::function::Fn::call::hcb7e699d3965606a@https://wgpu.rs/examples-gpu/wasm/hello-compute_bg.wasm:wasm-function[1166]:0x2ce2c
std::panicking::rust_panic_with_hook::h70a0e195f4db2a29@https://wgpu.rs/examples-gpu/wasm/hello-compute_bg.wasm:wasm-function[374]:0x1edff
std::panicking::begin_panic_handler::{{closure}}::hdcfc819ce836829e@https://wgpu.rs/examples-gpu/wasm/hello-compute_bg.wasm:wasm-function[444]:0x2211a
std::sys_common::backtrace::__rust_end_short_backtrace::h53cabafab5b09ada@https://wgpu.rs/examples-gpu/wasm/hello-compute_bg.wasm:wasm-function[822]:0x2b488
rust_begin_unwind@https://wgpu.rs/examples-gpu/wasm/hello-compute_bg.wasm:wasm-function[655]:0x28a33
core::panicking::panic_fmt::h751be80779d42b53@https://wgpu.rs/examples-gpu/wasm/hello-compute_bg.wasm:wasm-function[752]:0x2a677
core::panicking::panic::h8af046397a2bf65d@https://wgpu.rs/examples-gpu/wasm/hello-compute_bg.wasm:wasm-function[696]:0x2973d
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h12e2de3537e9fda4@https://wgpu.rs/examples-gpu/wasm/hello-compute_bg.wasm:wasm-function[182]:0x4ac8
wasm_bindgen_futures::task::singlethread::Task::run::hc86e56c7c205c89b@https://wgpu.rs/examples-gpu/wasm/hello-compute_bg.wasm:wasm-function[343]:0x1d2f3
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h6c46cd8c63f02dae@https://wgpu.rs/examples-gpu/wasm/hello-compute_bg.wasm:wasm-function[239]:0x14cb9
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hdf294bfac42f2bef@https://wgpu.rs/examples-gpu/wasm/hello-compute_bg.wasm:wasm-function[873]:0x2bc4a
__wbg_adapter_29@https://wgpu.rs/examples-gpu/wasm/hello-compute.js:212:10
real@https://wgpu.rs/examples-gpu/wasm/hello-compute.js:193:20
</pre>
</details>
<details>
<summary>wgpu.rs/compute error on Mac</summary>
device not found
</details>

**Platform**
MacOS with Ventura OSX

**Comment by ErichDonGubler** [comment] 2023-09-28 14:54
In case it's interesting to anyone, the tracking issue for general web compat. for @compute.toys is tracked here in Mozilla bug tracking: https://bugzilla.mozilla.org/show_bug.cgi?id=1831167

I encourage you to file a bug that blocks bug 1831167, since in the end, this is an issue with things running correctly on the Firefox platform, and we care about that. 🙂 It's also possible that this issue should _only_ be tracked there, if it's Firefox's fault and not `wgpu`'s. Since you're using WASM, though, it's entirely possible that _both_ might be at fault, so I don't think I can close this without understanding the issue better.

**Comment by ErichDonGubler** [comment] 2023-09-28 14:57
Interestingly, I see no error for [wgpu.rs/examples-gpu/?example=hello-compute](https://wgpu.rs/examples-gpu/?example=hello-compute) in 2023-09-28 Firefox Nightly on Windows 11. I wonder if this is Mac-specific?

On that note, the root of the issue seems to be `device not found` message from the OP. This sort of issue can happen if Firefox's copy of WGPU (which WGPU-compiled-to-WASM interfaces with) can't find a supported driver to work with. @munrocket, are you using (relatively recent) hardware that actually supports WebGPU? For instance, does the same page work in Chrome stable?

**Comment by teoxoy** [comment] 2023-09-28 15:47
> panicked at 'called Option::unwrap() on a None value', examples/hello-compute/src/main.rs:19:45

This is also most likely caused by failing to get an adapter.

https://github.com/gfx-rs/wgpu/blob/caad255737fc68c53ac1108b69acc2de27b3851d/examples/hello-compute/src/main.rs#L39-L41

The example could be improved to say that instead of panicking later on.

**Closed as completed** 2024-05-11 19:02 UTC
