### ISSUE TITLE
Bevy 0.14.2 with wgpu-hal-0.21.1 crashes on android at start

### ISSUE THREAD

**Issue by wentao** [gfx-rs/wgpu#6701] opened 2024-12-11 08:57 UTC
**Description**

I'm using bevy 0.14.2 to build an android game with very simple logic. You can find the project at https://github.com/80gen/bevy_ios_bug/tree/main/platforms/android/mini_android

**Repro steps**

1. Checkout the repo
2. Enter folder `platforms/android` and run command `cargo ndk -t arm64-v8a -o mini_android/app/src/main/jniLibs build`
3. Open Android Studio and open project at `platforms/android/mini_android`
4. Run app on android emulator

**Expected vs observed behavior**

The game crashed at start with the following log errors

```ignore
wgpu-hal heuristics assumed that the view dimension will be equal to `Cube` rather than `CubeArray`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.568 10064-10142 log event               com.egen.mini                        E  wgpu-hal heuristics assumed that the view dimension will be equal to `D2` rather than `D2Array`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.584 10064-10142 log event               com.egen.mini                        E  wgpu-hal heuristics assumed that the view dimension will be equal to `Cube` rather than `CubeArray`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.584 10064-10142 log event               com.egen.mini                        E  wgpu-hal heuristics assumed that the view dimension will be equal to `D2` rather than `D2Array`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.589 10064-10142 log event               com.egen.mini                        E  wgpu-hal heuristics assumed that the view dimension will be equal to `Cube` rather than `CubeArray`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.589 10064-10142 log event               com.egen.mini                        E  wgpu-hal heuristics assumed that the view dimension will be equal to `D2` rather than `D2Array`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.595 10064-10142 log event               com.egen.mini                        E  wgpu-hal heuristics assumed that the view dimension will be equal to `Cube` rather than `CubeArray`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.596 10064-10142 log event               com.egen.mini                        E  wgpu-hal heuristics assumed that the view dimension will be equal to `D2` rather than `D2Array`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.604 10064-10141 log event               com.egen.mini                        I  Only vertex shader is present. Creating an empty fragment shaderlog.target = "wgpu_hal::gles::device"; log.module_path = "wgpu_hal::gles::device"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/device.rs"; log.line = 401;
2024-12-11 00:37:14.604 10064-10138 RustStdoutStderr        com.egen.mini                        I  thread '<unnamed>' panicked at /Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/device.rs:1462:50:
2024-12-11 00:37:14.607 10064-10138 RustStdoutStderr        com.egen.mini                        I  Could not lock adapter context. This is most-likely a deadlock.
2024-12-11 00:37:14.607 10064-10138 RustStdoutStderr        com.egen.mini                        I  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-12-11 00:37:14.608 10064-10138 RustStdoutStderr        com.egen.mini                        I  Encountered a panic in system `bevy_render::renderer::render_system`!
2024-12-11 00:37:16.313 10064-10141 log event               com.egen.mini                        W  	Link: WARNING: Output of vertex shader '_vs2fs_location0' not read by fragment shader
WARNING: Output of vertex shader '_vs2fs_location7' not read by fragment shader
WARNING: Output of vertex shader '_vs2fs_location4' not read by fragment shader
log.target = "wgpu_hal::gles::device"; log.module_path = "wgpu_hal::gles::device"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/device.rs"; log.line = 430;
2024-12-11 00:37:16.352 10064-10141 log event               com.egen.mini                        E  Device::create_render_pipeline error: Internal error in ShaderStages(FRAGMENT) shader: The selected version doesn't support Features(CUBE_TEXTURES_ARRAY)log.target = "wgpu_core::device::global"; log.module_path = "wgpu_core::device::global"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.21.1/src/device/global.rs"; log.line = 1636;
2024-12-11 00:37:16.352 10064-10141 log event               com.egen.mini                        E  Shader translation error for stage ShaderStages(FRAGMENT): The selected version doesn't support Features(CUBE_TEXTURES_ARRAY)log.target = "wgpu::backend::wgpu_core"; log.module_path = "wgpu::backend::wgpu_core"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs"; log.line = 1179;
2024-12-11 00:37:16.352 10064-10141 log event               com.egen.mini                        E  Please report it to https://github.com/gfx-rs/wgpulog.target = "wgpu::backend::wgpu_core"; log.module_path = "wgpu::backend::wgpu_core"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs"; log.line = 1180;
2024-12-11 00:37:16.352 10064-10141 log event               com.egen.mini                        E  Handling wgpu errors as fatal by defaultlog.target = "wgpu::backend::wgpu_core"; log.module_path = "wgpu::backend::wgpu_core"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs"; log.line = 2995;
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I  thread 'Async Compute Task Pool (0)' panicked at /Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I  wgpu error: Validation Error
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I  
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I  Caused by:
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I      In Device::create_render_pipeline
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I        note: label = `pbr_opaque_mesh_pipeline`
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I      Internal error in ShaderStages(FRAGMENT) shader: The selected version doesn't support Features(CUBE_TEXTURES_ARRAY)
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I  
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I  
2024-12-11 00:37:19.831 10064-10070 com.egen.mini           com.egen.mini                        I  Thread[3,tid=10070,WaitingInMainSignalCatcherLoop,Thread*=0xb400007ab278eb20,peer=0x12d803f8,"Signal Catcher"]: reacting to signal 3
2024-12-11 00:37:19.831 10064-10070 com.egen.mini           com.egen.mini                        I  
2024-12-11 00:37:19.935 10064-10070 com.egen.mini           com.egen.mini                        I  Wrote stack traces to tombstoned
```

**Comment by Wumpf** [comment] 2024-12-11 11:54
Did this work with a previous version? According to the log output your android emulator has very limited rendering capabilities. You might need to update the android emulator as it is supposed to actually support Vulkan, see https://developer.android.com/studio/releases/emulator#29.0.6-vulkan
if that's already the case try forcing Vulkan.
(log indicates you're running with GLES)

**Comment by cwfitzgerald** [comment] 2024-12-11 15:23
This looks like at least partially a duplicate of https://github.com/gfx-rs/wgpu/issues/1614

**Comment by wentao** [comment] 2024-12-11 17:45
Yes, the issue is with emulator on macos. I tested on physical devices and it works fine.

**Closed as completed** 2024-12-12 06:20 UTC
