### ISSUE TITLE
set_push_constants: pipeline layout has no push constant range for the stage(s) FRAGMENT

### ISSUE THREAD

**Issue by dhardy** [gfx-rs/wgpu#1314] opened 2021-04-08 17:19 UTC
From what (little) I understand, this is a spurious error:
```
$ cargo run --example mandlebrot
   Compiling kas-wgpu v0.7.0 (/home/dhardy/projects/gui/kas/kas-wgpu)
    Finished dev [unoptimized + debuginfo] target(s) in 14.85s
     Running `/home/dhardy/.cache/cargo/debug/examples/mandlebrot`
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `render`
    In a set_push_constant command
    provided push constant is for stage(s) FRAGMENT, however the pipeline layout has no push constant range for the stage(s) FRAGMENT
```
To reproduce: use [this branch](https://github.com/kas-gui/kas/tree/push_const_frag_error) and run (from `kas-wgpu` dir) as above.

The code in question:
```rust
        wgpu::DeviceDescriptor {
            label: None,
            features: wgpu::Features::PUSH_CONSTANTS,
            limits: wgpu::Limits {
                max_push_constant_size: size_of::<PushConstants>().cast(),
                ..Default::default()
            },
        }
```
```rust
        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: None,
            bind_group_layouts: &[&bind_group_layout],
            push_constant_ranges: &[wgpu::PushConstantRange {
                stages: wgpu::ShaderStage::FRAGMENT,
                range: 0..size_of::<PushConstants>().cast(),
            }],
        });
```
```rust
                rpass.set_push_constants(
                    wgpu::ShaderStage::FRAGMENT,
                    0,
                    bytemuck::bytes_of(&window.push_constants),
                );
```

**Comment by kvark** [comment] 2021-04-08 20:25
Do you have the pipeline bound by the time you call `set_push_constants`? If not, then it's a dupe of #850

**Comment by cwfitzgerald** [comment] 2021-04-08 21:07
We should fix the error message at least, as this isn't terribly helpful

**Comment by dhardy** [comment] 2021-04-09 06:29
https://github.com/kas-gui/kas/blob/push_const_frag_error/kas-wgpu/examples/mandlebrot.rs#L250

No. I didn't see any doc regarding this requirement.

Thanks; that fixes it. Close?

**Comment by kvark** [comment] 2021-04-09 14:08
@dhardy it's not a requirement, it's just a bug in the implementation of push constant today (the #850).
So we can close this and keep the original bug for fixing.

**Closed by kvark** 2021-04-09 14:08 UTC

**Comment by dhardy** [comment] 2021-04-09 15:07
My render pass currently looks like:
```rust
let mut rpass = encoder.begin_render_pass(..);
rpass.set_scissor_rect(..);
pipe1.render(&mut pass);
pipe2.render(&mut pass);
..

impl MyPipeX {
    pub fn render(&'a self, rpass: &mut wgpu::RenderPass<'a>) {
        let count = self.vertices.len().cast();
        rpass.set_pipeline(self.pipe);
        rpass.set_bind_group(0, self.bind_group, &[]);
        rpass.set_vertex_buffer(0, self.buffer.slice(..));
        rpass.draw(0..count, 0..1);
    }
}
```
Is this kind of thing valid? If it is, how does setting the push constants before setting the pipeline even work?

**Comment by kvark** [comment] 2021-04-09 15:21
Push constants are a part of the resource binding model. So binding them before the pipeline should work exactly the same way as binding the resource groups before the pipeline.
FWIW, this code looks fine.

**Comment by dhardy** [comment] 2021-04-13 14:37
Following on from the above, is there a limit on the number of pipelines per render pass?

Because I have added another render pipeline and found it won't render anything unless I remove one of the others (actually, behaviour depends on which other one is removed).

`wgpu::Limits` has `max_bind_groups` — is this the limiting factor? And if I want my code to work everywhere is it better to use a separate render pass than increase this?

**Comment by kvark** [comment] 2021-04-13 14:40
there is no limit on the number of pipelines, or the size of a render pass

**Comment by dhardy** [comment] 2021-04-13 14:46
Thanks for the quick answer. This leaves me confused then — something weird is happening.

**Comment by kvark** [comment] 2021-04-13 14:48
Please try to debug with RenderDoc, see https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications
If unable to investigate on your own, please file an issue, and attach an API trace

**Comment by dhardy** [comment] 2021-04-14 09:50
This is where I'm at:

- done code cleanup, nothing obvious
- tested on a second computer with the same result (both Fedora linux, one AMD the other Intel graphics)

To reproduce:

- use [this PR](https://github.com/kas-gui/kas/pull/184) (current hash b6c37ea)
- `cd kas-wgpu && cargo +nightly run --example gallery` (needs nightly or beta) — no image drawn (also a resize bug that I haven't got to yet)
- comment out `draw_pipe.rs:224` (ss render) and run again — some UI isn't drawn but the image is

I'll try doing some more debugging but not quite sure what to do next. In RenderDoc it looks like there's a missing draw.

**Comment by kvark** [comment] 2021-04-14 13:40
Is this reproducible with an API trace? Could you attach one here?
