### ISSUE TITLE
Backends::all() really does mean every backend

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu#1796] opened 2021-08-13 11:38 UTC
using Backends::all() results in every backend being initialized or at least thats what it seems to be doing.
The hello-triangle example in master currently fails with:
```
[2021-08-13T11:30:37Z ERROR wgpu_core::device] surface configuration failed: Native window is in use
thread 'main' panicked at 'Error in Surface::configure: invalid surface', wgpu/src/backend/direct.rs:186:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
   2: wgpu::backend::direct::Context::handle_error_fatal
             at ./src/backend/direct.rs:186:9
   3: <wgpu::backend::direct::Context as wgpu::Context>::surface_configure
             at ./src/backend/direct.rs:891:13
   4: wgpu::Surface::configure
             at ./src/lib.rs:3089:9
   5: hello_triangle::run::{{closure}}
             at ./examples/hello-triangle/main.rs:75:5
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/mod.rs:80:19
   7: pollster::block_on
             at /home/rukai/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.4/src/lib.rs:132:15
   8: hello_triangle::main
             at ./examples/hello-triangle/main.rs:139:9
   9: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

We can fix the example by replacing Backends::all() with Backends::PRIMARY.

But trying to enable every backend at once sounds absurd so I assume the fix is to make it not do that?

**Platform**
wgpu master, linux, EVERY BACKEND AT ONCE, Nvidia GTX 960 with proprietary driver

**Comment by kvark** [comment] 2021-08-13 14:33
I think this is a duplicate of #1153.

**Closed by kvark** 2021-08-13 14:33 UTC

**Comment by rukai** [comment] 2021-08-14 05:07
Oh, it is a duplicate, but its a duplicate of this issue https://github.com/gfx-rs/wgpu/issues/1492

**Comment by kvark** [comment] 2021-08-14 05:09
Ah, sorry, ok, thanks for correction!
