### ISSUE TITLE
I run example then Terminal error

### ISSUE THREAD

**Issue by SunOfHomeBoy** [gfx-rs/wgpu#3771] opened 2023-05-12 08:42 UTC
**Description**
win11 
> mkdir -p trace && WGPU_TRACE=trace cargo run --features trace --example boids

![image](https://github.com/gfx-rs/wgpu/assets/30047595/ea3fe4da-1670-43d7-b988-bc5a3638e7b4)

code is runing,but Terminal  crazy error....

![image](https://github.com/gfx-rs/wgpu/assets/30047595/c06bbcf3-533a-4bdf-9047-180f93429876)

AI tips：
![image](https://github.com/gfx-rs/wgpu/assets/30047595/e9831ca7-3930-4983-97ff-96249b60fadf)

**Repro steps**
Ideally, a runnable example we can check out.

**Expected vs observed behavior**
Clearly describe what you get, and how it goes across your expectations.

**Extra materials**
Screenshots to help explain your problem.
Validation logs can be attached in case there are warnings and errors.
Zip-compressed API traces and GPU captures can also land here.

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.

![image](https://github.com/gfx-rs/wgpu/assets/30047595/80a2b168-4315-4553-afb7-b156feabf2f3)

设备名称	DESKTOP-0M2EPFH
处理器	AMD Ryzen 7 5700G with Radeon Graphics            3.80 GHz
机带 RAM	32.0 GB (31.8 GB 可用)

![image](https://github.com/gfx-rs/wgpu/assets/30047595/25a179a6-6a64-44a8-b46e-0d4f5b299702)

**Comment by teoxoy** [comment] 2023-06-05 21:51
This is a duplicate of https://github.com/gfx-rs/wgpu/issues/3733

**Closed as not planned by teoxoy** 2023-06-05 21:51 UTC
