### ISSUE TITLE
Specifying an unsupported MSAA sample count leads to an obscure crash in Rendy

### ISSUE THREAD

**Issue by HadrienG2** [gfx-rs/wgpu#324] opened 2019-09-02 21:20 UTC
To reproduce this, take the msaa-line example from wgpu-rs, and increase the sample count with the right keyboard arrow until reaching a value that is not supported by the host GPU.

On my particular Vulkan implementation (Radeon RX 560 + amdgpu driver from linux 5.2.10 + Mesa 19.1.5), the following crash will ensue:

```
Press left/right arrow keys to change sample_count.
sample_count: 4
sample_count: 8
sample_count: 16
thread 'main' panicked at 'assertion failed: align.is_power_of_two()', /home/hadrien/.cargo/registry/src/github.com-1ecc6299db9ec823/rendy-memory-0.4.0/src/allocator/dynamic.rs:508:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:411
   8: <rendy_memory::allocator::dynamic::DynamicAllocator<B> as rendy_memory::allocator::Allocator<B>>::alloc
             at /home/hadrien/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/b58c96e/wgpu-native/<::std::macros::panic macros>:4
   9: rendy_memory::heaps::memory_type::MemoryType<B>::alloc_impl
             at /home/hadrien/.cargo/registry/src/github.com-1ecc6299db9ec823/rendy-memory-0.4.0/src/heaps/memory_type.rs:99
  10: rendy_memory::heaps::memory_type::MemoryType<B>::alloc
             at /home/hadrien/.cargo/registry/src/github.com-1ecc6299db9ec823/rendy-memory-0.4.0/src/heaps/memory_type.rs:63
  11: rendy_memory::heaps::Heaps<B>::allocate_from
             at /home/hadrien/.cargo/registry/src/github.com-1ecc6299db9ec823/rendy-memory-0.4.0/src/heaps/mod.rs:173
  12: rendy_memory::heaps::Heaps<B>::allocate
             at /home/hadrien/.cargo/registry/src/github.com-1ecc6299db9ec823/rendy-memory-0.4.0/src/heaps/mod.rs:141
  13: wgpu_native::device::Device<B>::create_texture
             at /home/hadrien/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/b58c96e/wgpu-native/src/device.rs:683
  14: wgpu_native::device::device_create_texture
             at /home/hadrien/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/b58c96e/wgpu-native/src/device.rs:842
  15: wgpu_device_create_texture
             at /home/hadrien/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/b58c96e/wgpu-native/src/device.rs:863
  16: wgpu::Device::create_texture
             at src/lib.rs:815
  17: msaa_line::Example::create_multisampled_framebuffer
             at examples/msaa-line/main.rs:99
  18: <msaa_line::Example as msaa_line::framework::Example>::render
             at examples/msaa-line/main.rs:188
  19: msaa_line::framework::run::{{closure}}
             at examples/msaa-line/../framework.rs:149
  20: winit::platform_impl::platform::sticky_exit_callback
             at /home/hadrien/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha3/src/platform_impl/linux/mod.rs:656
  21: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/hadrien/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha3/src/platform_impl/linux/x11/mod.rs:298
  22: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/hadrien/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha3/src/platform_impl/linux/x11/mod.rs:382
  23: winit::platform_impl::platform::EventLoop<T>::run
             at /home/hadrien/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha3/src/platform_impl/linux/mod.rs:603
  24: winit::event_loop::EventLoop<T>::run
             at /home/hadrien/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha3/src/event_loop.rs:140
  25: msaa_line::framework::run
             at examples/msaa-line/../framework.rs:112
  26: msaa_line::main
             at examples/msaa-line/main.rs:226
  27: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  28: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  29: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  30: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  31: std::panicking::try
             at src/libstd/panicking.rs:275
  32: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  33: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  34: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  35: main
  36: __libc_start_main
             at ../csu/libc-start.c:308
  37: _start
```

My understanding is that this happens because wgpu does not validate the sample count parameter to `create_texture` before calling into gfx-hal, gets garbage image alignment requirements from either HAL or the driver as a result, and passes these down to Rendy's allocator without further consideration.

I think that crashing in response to such invalid demands is fine, but it would be nice if the crash occured in a more reasonable place, and with a more reasonable error message.

**Comment by HadrienG2** [comment] 2019-09-03 07:14
Come to think of it, safe APIs like wgpu actually _must_ validate their inputs before calling into the driver, because Vulkan [treats invalid API usage as UB](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#fundamentals-errors):

> The core layer assumes applications are using the API correctly. Except as documented elsewhere in the Specification, the behavior of the core layer to an application using the API incorrectly is undefined, and may include program termination.

So unlike in OpenGL, one cannot use the approach of calling the driver first, and checking for errors after the fact.

**Comment by kvark** [comment] 2019-09-03 13:21
@HadrienG2 yes, this is correct. We aim to validate *everything*, such that any program is guaranteed to execute portably without UB. Hence the "validation" label on the issue.

The biggest problem though is not validation - it's the spec itself: how to write it such that some useful limits are written down in the spec itself, and how to provide a way to opt for more. Unlike device-level limits, the MSAA count may depend on the texture parameters, so it's hard to standardize. We'll work on that within the group.

**Comment by cwfitzgerald** [comment] 2020-12-01 18:03
This should be validated for now and the samples is a dupe of #804.

**Closed by cwfitzgerald** 2020-12-01 18:03 UTC
Labels: area: validation, type: bug
