### ISSUE TITLE
Cube example crashes when minimizing the window

### ISSUE THREAD

**Issue by YuuriMomo** [gfx-rs/wgpu#896] opened 2020-08-25 10:02 UTC
**Description**
When running cube example and minimizing the window on windows the cube example crashes

**Repro steps**
Ideally, a runnable example we can check out.
https://github.com/gfx-rs/wgpu-rs 7396e92

**Expected vs observed behavior**
Window should minimize without crashing.

Program crashes when minimizing

**Extra materials**
Screenshots to help explain your problem.
Validation logs can be attached in case there are warnings and errors.
Zip-compressed API traces and GPU captures can also land here.
![obraz](https://user-images.githubusercontent.com/53386725/91160790-2367aa00-e6ca-11ea-8a7a-eee8acf0d20c.png)

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.
Windows 10 version 2004
GPU: 1050ti
CPU i5-8300H

**Comment by kvark** [comment] 2020-08-25 16:36
Let's consider this a dupe of https://github.com/gfx-rs/wgpu-rs/issues/316

**Closed by kvark** 2020-08-25 16:36 UTC
