### ISSUE TITLE
Copying CPU buffer to GPU buffer bug on Linux/Vulkan

### ISSUE THREAD

**Issue by KeKsBoTer** [gfx-rs/wgpu#2480] opened 2022-02-15 17:02 UTC
**Description**
Copying an image buffer from CPU to GPU texture with `write_texture` gives unexpected result on linux.

**Repro steps**

1. Create texture
```rust
  let frame_buffer = device.create_texture(&wgpu::TextureDescriptor {
            label: None,
            size: Extent3d {
                width: 100,
                height: 100,
                depth_or_array_layers: 1,
            },
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::Rgba8Unorm,
            usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
        });
```

2. Create CPU buffer and write some data into it
```rust
let mut cpu_buffer = vec![0u8;100*100*4];
for i in 0..100{
    for i in 0..100{
         let index = (i*100+j)*4;
         // write some data here
         cpu_buffer[index] = i as u8;
         cpu_buffer[index+1] = 0;
         cpu_buffer[index+2] = 0;
         cpu_buffer[index+3] = 255;
    }
}
```
 3. copy data to GPU buffer with `write_texture`
 
 ```rust
queue.write_texture(
    frame_buffer.as_image_copy(),
    &cpu_buffer,
    wgpu::ImageDataLayout {
        offset: 0,
        bytes_per_row: Some(std::num::NonZeroU32::new(100 * 4).unwrap()),
        rows_per_image: None,
    },
    wgpu::Extent3d {
        width: 100,
        height: 100,
        depth_or_array_layers: 1,
    },
);
``` 

4. Render texture to screen

**Expected vs observed behavior**

Image on linux looks like on macOS.
But image on linux is distorted.

![Screenshot macOS](https://user-images.githubusercontent.com/14186588/154108738-b1c6d74e-712b-405b-bcd5-84b0f58437e6.png)
![Screenshot Linux](https://user-images.githubusercontent.com/14186588/154108754-a0967ce8-f333-4f31-8df9-8ae66678a6a3.png)

**Extra materials**

I used only the column number as red value:

![100x100 image where red equals column](https://user-images.githubusercontent.com/14186588/154110632-5288ee43-a879-43c3-ab3c-daf50b8ac9db.png)

I used only the row number as red value:

![100x100 image where red equals row](https://user-images.githubusercontent.com/14186588/154110885-94110dcc-3835-4daa-af02-26fdb6bfa15f.png)

**Platform**
Linux (Ubuntu 21.10)
macOS (12.2.1)

wgpu (0.12.0)

**Comment by kvark** [comment] 2022-02-15 19:10
Thank you for filing! Would you be able to modify one of our examples to reproduce the issue? Alternatively, attaching a zipped trace would help - https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications#tracing-infrastructure.

**Comment by KeKsBoTer** [comment] 2022-02-15 22:29
Update:

I just realized this issue is only present if I use my integrated GPU (Intel(R) HD Graphics 4600 (HSW GT2) (Vulkan)).
When running on my dedicated GPU (AMD RADV TONGA (Vulkan)) the issue does not occur.

The issue does also occur with the cube example! 
![image](https://user-images.githubusercontent.com/14186588/154159420-5c25d330-6f6b-46d0-a921-46dd8e1416e1.png)

I created a trace for the cube example: [trace.zip](https://github.com/gfx-rs/wgpu/files/8075135/trace.zip)

**Comment by kvark** [comment] 2022-02-15 22:40
Wow that's unexpected. I can't reproduce this on my Intel Xe GPU on Linux, from either the example itself or from the trace :(
Looks like we may be dealing with a driver bug here. Would you be able to record the first frame in RenderDoc and shader that capture?

**Comment by KeKsBoTer** [comment] 2022-02-21 11:46
I tried to record a Frame with RenderDoc. 
Turns out Wayland is not supported yet ([Issue](https://github.com/baldurk/renderdoc/issues/853)).

When I run the example with X11 (and not Wayland, as before) the issue is not present. 

Seems like it is a problem with Wayland. 
Any Idea what could cause this and If its wgpus's fault?

**Comment by kvark** [comment] 2022-02-24 04:27
> When I run the example with X11 (and not Wayland, as before) the issue is not present.

That's kind of puzzling. Texture data uploads should have nothing to do with Wayland and whatnot.

**Comment by cwfitzgerald** [comment] 2023-10-14 02:57
This seems like a driver bug, so closing as out of scope.

**Closed by cwfitzgerald** 2023-10-14 02:57 UTC
Labels: type: bug, api: vulkan
