### ISSUE TITLE
Linux X11 — create_swap_chain with zero area triggers validation error and crash

### ISSUE THREAD

**Issue by benfrankel** [gfx-rs/wgpu#887] opened 2020-08-20 01:04 UTC
**Description**
Calling `Device::create_swap_chain` with a `SwapChainDescriptor` that has `width` and `height` set to `0` triggers a Vulkan validation error (`VUID-VkSwapchainCreateInfoKHR-imageExtent-01689`) and crashes the application with `malloc(): invalid size (unsorted)`.

**Repro steps**
1. Patch `wgpu-rs`'s cube example in `examples/cube/main.rs` with:
    ```rust
    impl Example {
        fn generate_matrix(mut aspect_ratio: f32) -> cgmath::Matrix4<f32> {
            if aspect_ratio.is_nan() {
                aspect_ratio = 1.0;
            }
    ...
    ```
    So it doesn't crash early due to `thread 'main' panicked at 'The aspect ratio cannot be below zero, found: NaN'`.

2. Add this line to the i3 config:
    ```
    assign [class="^cube$"] workspace "foo"
    ```
    So the application window is immediately moved to a different, not-open workspace when it's created.

3. Run the example (`cargo run --example cube`).

**Expected vs observed behavior**
- **Expected:** Error or panic.
- **Observed:** Validation error and crash.

**Platform**
- Linux 5.7.12-arch1-1
- X11
- i3 window manager
- wgpu v0.6.0

**Comment by benfrankel** [comment] 2020-08-20 01:06
Btw, I'm not sure if this issue should go on the `wgpu-rs` repo or this repo.

**Comment by kvark** [comment] 2020-08-20 05:38
Thank you for filing! This repo is proper, although it's trivial for us to transfer issues if needed.

**Comment by rukai** [comment] 2020-08-20 06:33
You can also reproduce this by just minimizing the examples on windows.

**Comment by cwfitzgerald** [comment] 2020-12-01 17:05
Dupe of #1026

**Closed by cwfitzgerald** 2020-12-01 17:05 UTC
Labels: area: validation, help wanted, type: bug
