### ISSUE TITLE
[wgsl-in] parsing error for unbounded `binding_array` of storage textures

### ISSUE THREAD

**Issue by Wumpf** [gfx-rs/wgpu#5765] opened 2024-06-01 20:56 UTC
Naga fails parsing this code
```
var images: binding_array<texture_storage_2d<rgba32float, read_write>>;
```
With:
```
Shader 'computepass-bindless.wgsl' parsing error: expected '>', found '>>'
  ┌─ wgsl:5:69
  │
5 │ var images: binding_array<texture_storage_2d<rgba32float, read_write>>;
  │                                                                     ^^ expected '>'


    expected '>', found '>>'
```

Curiously, adding a whitespace between the angle brakets makes it compile fine:
```
var images: binding_array<texture_storage_2d<rgba32float, read_write> >;
```

**Comment by jimblandy** [comment] 2024-06-03 16:50
Closing as duplicate of #4501.

**Closed as completed by jimblandy** 2024-06-03 16:50 UTC
Labels: type: bug, area: naga front-end, lang: WGSL
