### ISSUE TITLE
wasm/webgl2: buggy ClearColor behavior on various platforms

### ISSUE THREAD

**Issue by rparrett** [gfx-rs/wgpu#2909] opened 2022-07-22 22:38 UTC
**Description**

Clear color is darker than expected, but occasionally flickers with the correct color.

**Repro steps**

With an M1 Mac, open Chrome (stable) and visit https://wgpu.rs/examples-gl/?example=cube or https://wgpu.rs/examples-gl/?example=mipmap

Alternately, with Win10 in Firefox follow instructions in the linked bevy issue.

**Expected vs observed behavior**

Expected a light blue background color, but I see a dark blue color that occasionally flickers light blue.

**Extra materials**

https://user-images.githubusercontent.com/200550/180576975-4b3c732b-9740-4ddd-8f85-41cc0299e237.mp4

See also: https://github.com/bevyengine/bevy/issues/5426

With bevy in the loop, we're also seeing strange Clear color behavior on Windows in Firefox but I'm so far unsuccessful in reproducing this in a wgpu example.

**Platform**

This seems to occur only in Stable Chrome for me, so I suppose the issue will eventually fix itself?

Here's the results of testing on various browsers that I have access to on this machine.

||Browser|AdapterInfo|
|-|-|-|
|**Bug**|Chrome 103.0.5060.114|AdapterInfo { name: "ANGLE (Apple, Apple M1 Max, OpenGL 4.1)", vendor: 0, device: 0, device_type: IntegratedGpu, backend: Gl }|
|**Bug**|Chrome 103.0.5060.134|AdapterInfo { name: "ANGLE (Apple, Apple M1 Max, OpenGL 4.1)", vendor: 0, device: 0, device_type: IntegratedGpu, backend: Gl }|
|Ok|Chrome Canary 105.0.5195.0|AdapterInfo { name: "ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Max, Version 12.2.1 (Build 21D62))", vendor: 0, device: 0, device_type: IntegratedGpu, backend: Gl }|
|Ok|Chrome Canary 105.0.5195.2|AdapterInfo { name: "ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Max, Version 12.2.1 (Build 21D62))", vendor: 0, device: 0, device_type: IntegratedGpu, backend: Gl }|
|Ok|Safari 15.3 (17612.4.9.1.8)|AdapterInfo { name: "Apple GPU", vendor: 0, device: 0, device_type: Other, backend: Gl }|
|Ok|Firefox 102.0.1|AdapterInfo { name: "Apple M1", vendor: 0, device: 0, device_type: IntegratedGpu, backend: Gl }|
|Ok|Firefox Nightly 104.0a1|AdapterInfo { name: "Apple M1", vendor: 0, device: 0, device_type: IntegratedGpu, backend: Gl }|

**Comment by joshpauline** [comment] 2022-07-26 08:48
I also get this issue on my apple m1 when rendering, would be interesting to see what the issue is

**Comment by rparrett** [comment] 2022-08-17 19:10
Worked on this a bit a while back with cwfitzgerald in the bevy discord. Reposting the information here for visibility.

Patching [this file](https://github.com/gfx-rs/wgpu/blob/259991e2589f01b6561a9daa9ff63d629c802c15/wgpu-hal/src/gles/adapter.rs#L511 ) to unconditionally set the `MESA_I915_SRGB_SHADER_CLEAR` resolves the issue for me on MacOS.

The issue on Windows that requires the slightly more involved repro in the linked Bevy issue may be a completely separate issue, because the patch above does not seem to help there.

**Comment by maaku** [comment] 2024-07-06 19:50
I think I may have run into this same issue, on an Apple M1 device in both Safari and Brave. The error log contains "WebGL: INVALID_OPERATION: drawBuffers: COLOR_ATTACHMENTi or NONE". The render pass with a clear color is the following:

```rust
    pub fn run(&self, encoder: &mut wgpu::CommandEncoder, frame: &wgpu::TextureView) {
        let mut rpass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
            label: None,
            color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                view: frame,
                resolve_target: None,
                ops: wgpu::Operations {
                    load: wgpu::LoadOp::Clear(wgpu::Color {
                        r: 0.8,
                        g: 0.8,
                        b: 0.8,
                        a: 1.0,
                    }),
                    store: wgpu::StoreOp::Store,
                },
            })],
            depth_stencil_attachment: None,
            timestamp_writes: None,
            occlusion_query_set: None,
        });

        rpass.execute_bundles(Some(&self.render_bundle));
    }
```

Note the background color is a light gray. What I actually see is black, and no flickering. It is being cleared because as I move objects around they don't persist in the frame buffer, but the clear color is not being applied.

The proposed workaround of forcing `MESA_I915_SRGB_SHADER_CLEAR` doesn't fix it.

**Comment by maaku** [comment] 2024-07-06 20:31
I found that latest wgpu trunk works. I bisected to commit 65d8c94afd825cbed454af449712d408decbef6b, part of #5666, which solved the issue for me. Maybe it solve's OP's problem as well?

**Comment by teoxoy** [comment] 2024-07-08 07:28
@rparrett @0xfourzerofour could you confirm?

**Comment by rparrett** [comment] 2024-07-08 15:30
I am no longer able to reproduce on the machines I have access to, either before or after https://github.com/gfx-rs/wgpu/commit/65d8c94afd825cbed454af449712d408decbef6b.

Win11 Firefox 127.0.2
Win11 Chrome 126.0.6478.127
macOS Firefox 127.0.2
macOS Chrome 126.0.6478.127

I pinged another Bevy user who as able to reproduce slightly more recently.

**Comment by teoxoy** [comment] 2024-07-09 07:59
Let's close this as resolved but please leave a comment or reopen if that's not the case.

**Closed by teoxoy** 2024-07-09 07:59 UTC
Labels: type: enhancement, help required, external: driver-bug, api: gles
