### ISSUE TITLE
Segfault when running hello-compute

### ISSUE THREAD

**Issue by lucasyvas** [gfx-rs/wgpu#3633] opened 2023-04-02 03:27 UTC
**Description**

Segfault when running compute example.

**Repro steps**

`cargo run --example hello-compute`

**Expected vs observed behavior**

Expected it to not segfault - first noticed the issue in `iced-rs` but the backtrace leads to the same spot here.

**Extra materials**

gdb

```
lucas@watchtower:~/git/wgpu/target/debug/examples$ gdb -ex 'set pagination off' ./hello-compute
GNU gdb (Ubuntu 10.2-0ubuntu1~18.04~2) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./hello-compute...
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /home/lucas/git/wgpu/target/debug/examples/hello-compute.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) run
Starting program: /home/lucas/git/wgpu/target/debug/examples/hello-compute 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
No numbers were provided, defaulting to [1, 2, 3, 4]
[New Thread 0x7fffeb44f700 (LWP 21147)]
[New Thread 0x7fffeac4e700 (LWP 21148)]
[New Thread 0x7fffea44d700 (LWP 21149)]
[New Thread 0x7fffe9c4c700 (LWP 21150)]
[New Thread 0x7fffe930a700 (LWP 21151)]
[New Thread 0x7fffe8b09700 (LWP 21152)]
[New Thread 0x7fffd3fff700 (LWP 21153)]
[New Thread 0x7fffd37fe700 (LWP 21154)]

Thread 1 "hello-compute" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) backtrace
#0  0x0000000000000000 in ?? ()
#1  0x0000555555ebff4e in ash::extensions::ext::debug_utils::DebugUtils::cmd_insert_debug_utils_label (self=0x555556673e38, command_buffer=..., label=0x7fffffff7a50) at /home/lucas/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.37.2+1.3.238/src/extensions/ext/debug_utils.rs:87
#2  0x0000555555dd3af1 in wgpu_hal::vulkan::command::{impl#2}::insert_debug_marker (self=0x555556b93ea8, label=...) at wgpu-hal/src/vulkan/command.rs:555
#3  0x00005555558fe1ed in wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::command_encoder_run_compute_pass_impl<wgpu_core::hub::IdentityManagerFactory, wgpu_hal::vulkan::Api> (self=0x555556951000, encoder_id=..., base=...) at wgpu-core/src/command/compute.rs:708
#4  0x00005555558fc725 in wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::command_encoder_run_compute_pass<wgpu_core::hub::IdentityManagerFactory, wgpu_hal::vulkan::Api> (self=0x555556951000, encoder_id=..., pass=0x555556b93dd0) at wgpu-core/src/command/compute.rs:323
#5  0x0000555555bb30a9 in wgpu::backend::direct::{impl#7}::command_encoder_end_compute_pass (self=0x555556951000, encoder=0x7fffffffbad0, encoder_data=0x555556b80d50, _pass=0x7fffffffbad8, pass_data=0x555556b93dd0) at wgpu/src/backend/direct.rs:1835
#6  0x0000555555a4ee40 in wgpu::context::{impl#5}::command_encoder_end_compute_pass<wgpu::backend::direct::Context> (self=0x555556951000, encoder=0x7fffffffd9f8, encoder_data=..., pass=0x7fffffffbec8, pass_data=...) at wgpu/src/context.rs:2627
#7  0x0000555555b46b83 in wgpu::{impl#59}::drop (self=0x7fffffffbec8) at wgpu/src/lib.rs:3658
#8  0x00005555556999e7 in core::ptr::drop_in_place<wgpu::ComputePass> () at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ptr/mod.rs:487
#9  0x0000555555694830 in hello_compute::execute_gpu_inner::{async_fn#0} () at wgpu/examples/hello-compute/main.rs:140
#10 0x00005555556972c1 in core::future::from_generator::{impl#1}::poll<hello_compute::execute_gpu_inner::{async_fn_env#0}> (self=..., cx=0x7fffffffd6b8) at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91
#11 0x0000555555693cd8 in hello_compute::execute_gpu::{async_fn#0} () at wgpu/examples/hello-compute/main.rs:63
#12 0x0000555555697111 in core::future::from_generator::{impl#1}::poll<hello_compute::execute_gpu::{async_fn_env#0}> (self=..., cx=0x7fffffffd6b8) at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91
#13 0x0000555555692eec in hello_compute::run::{async_fn#0} () at wgpu/examples/hello-compute/main.rs:19
#14 0x000055555569720b in core::future::from_generator::{impl#1}::poll<hello_compute::run::{async_fn_env#0}> (self=..., cx=0x7fffffffd6b8) at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91
#15 0x000055555568e3da in pollster::block_on<core::future::from_generator::GenFuture<hello_compute::run::{async_fn_env#0}>> (fut=...) at /home/lucas/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.5/src/lib.rs:125
#16 0x0000555555696ce1 in hello_compute::main () at wgpu/examples/hello-compute/main.rs:186
```

**Platform**

```
OS: Ubuntu 18.04.6 LTS x86_64 
Kernel: 5.4.0-146-generic 
Uptime: 6 hours, 16 mins 
CPU: Intel i7-7500U (4) @ 3.500GHz 
GPU: Intel HD Graphics 620                      
```

**Comment by cwfitzgerald** [comment] 2023-04-12 20:41
I believe this is an issue with Mesa that was quite recently fixed.

**Comment by jimblandy** [comment] 2023-04-12 21:26
Yes - I think this is a duplicate of #3377.

**Closed by jimblandy** 2023-04-12 21:26 UTC
