### ISSUE TITLE
`cargo test --test wgpu-tests drop_encoder` triggers VUID-VkInstanceCreateInfo-flags-06559

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#4037] opened 2023-08-11 20:22 UTC
When I run the command `cargo test --test wgpu-tests drop_encoder`, the Vulkan validation layer reports a violation of [`VUID-VkInstanceCreateInfo-flags-06559`](https://registry.khronos.org/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkInstanceCreateInfo-flags-06559).

I'm guessing this was introduced by #3958, in the process of fixing other things.
cc @schell 

```
$ cargo test --test wgpu-tests drop_encoder
    Finished test [unoptimized + debuginfo] target(s) in 0.11s
     Running tests/root.rs (target/debug/deps/wgpu_tests-524dfc4694b78a69)

running 1 test
VUID-VkInstanceCreateInfo-flags-06559(ERROR / SPEC): msgNum: -155949925 - Validation Error: [ VUID-VkInstanceCreateInfo-flags-06559 ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xf6b4649b | vkCreateInstance(): pCreateInfo->flags has VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR set, but pCreateInfo->ppEnabledExtensionNames does not include VK_KHR_portability_enumeration The Vulkan spec states: If flags has the VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR bit set, the list of enabled extensions in ppEnabledExtensionNames must contain VK_KHR_portability_enumeration (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkInstanceCreateInfo-flags-06559)
    Objects: 1
        [0] 0, type: 1, name: NULL
test encoder::drop_encoder ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 53 filtered out; finished in 0.08s

$ 
```

**Comment by cwfitzgerald** [comment] 2023-08-11 20:28
Dupe of #4004

**Closed as not planned by cwfitzgerald** 2023-08-11 20:28 UTC
Labels: type: bug, area: validation, area: correctness, backend: vulkan
