### ISSUE TITLE
`UsageMismatch` error on creating querry buffer without `MAPPABLE_PRIMARY_BUFFERS` feature

### ISSUE THREAD

**Issue by pannapudi** [gfx-rs/wgpu#3725] opened 2023-04-24 10:51 UTC
**Description**
I got this error by updating `wgpu` to "0.16.0" and [`wgpu-profiler`](https://github.com/Wumpf/wgpu-profiler/) to "0.12.0" versions.

```bash
[2023-04-23T09:50:21Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
The application panicked (crashed).
Message:  wgpu error: Validation Error

Caused by:
    In Device::create_buffer
      note: label = `GpuProfiler - Query Buffer`
    `MAP` usage can only be combined with the opposite `COPY`, requested BufferUsages(MAP_READ | QUERY_RESOLVE)
```

Snippet of the buffer creation [code](https://github.com/Wumpf/wgpu-profiler/blob/main/src/lib.rs#L443) from `wgpu-profiler`
```rust
            buffer: device.create_buffer(&wgpu::BufferDescriptor {
                label: Some("GpuProfiler - Query Buffer"),
                size: (QUERY_SIZE * capacity) as u64,
                usage: wgpu::BufferUsages::QUERY_RESOLVE | wgpu::BufferUsages::MAP_READ,
                mapped_at_creation: false,
            }),
```

**Potential fix**
`UsageMismatch` error appears only in one place, listed below, and perhaps can be resolved by adding `QUERY_RESOLVE` along with `COPY_DST` to `read_mismatch`, but I don't know how it will affect other parts of the code.
```rust
        if !self
            .features
            .contains(wgt::Features::MAPPABLE_PRIMARY_BUFFERS)
        {
            use wgt::BufferUsages as Bu;
            let write_mismatch = desc.usage.contains(Bu::MAP_WRITE)
                && !(Bu::MAP_WRITE | Bu::COPY_SRC).contains(desc.usage);
            let read_mismatch = desc.usage.contains(Bu::MAP_READ)
                && !(Bu::MAP_READ | Bu::COPY_DST).contains(desc.usage);
            if write_mismatch || read_mismatch {
                return Err(resource::CreateBufferError::UsageMismatch(desc.usage));
            }
        }
 ```

***Extra***
`[2023-04-23T09:50:21Z ERROR wgpu::backend::direct] Handling wgpu errors **as** fatal by default`
Is that a typo?

**Comment by Wumpf** [comment] 2023-04-24 14:02
I think wgpu's error is actually correct, this is how `MAP_READ` is specified, it can only be combined with `COPY_DST`. See https://www.w3.org/TR/webgpu/#buffer-usage

This is on me for not testing a user contributed update to `wgpu-profiler` - these days I'm most of the time on a Mac and I couldn't see the bug there since queries don't work there yet, should have tested on Windows or Linux.

As I understand `wgpu-profiler` needs to use buffers with `QUERY_RESOLVE | COPY_SRC` and then copy to another buffer with `COPY_DST | MAP_READ` to do the actual readback. PRs welcome..

**Comment by Wumpf** [comment] 2023-04-24 14:20
It did work for the original contributor though! See https://github.com/Wumpf/wgpu-profiler/pull/26

EDIT: Seems because of use of `MAPPABLE_PRIMARY_BUFFERS` feature

**Comment by teoxoy** [comment] 2023-04-24 17:53
Seems this is working as intended, closing.

**Closed as not planned by teoxoy** 2023-04-24 17:53 UTC
