### ISSUE TITLE
Gettin error[E0658]: `match` is not allowed in a `const fn` when trying to compile ruffle from AUR

### ISSUE THREAD

**Issue by Managor** [gfx-rs/wgpu#1131] opened 2021-01-05 11:42 UTC
**Description**
When trying to compile ruffle for AUR https://aur.archlinux.org/packages/ruffle-git/, the compiler outputs this 
```
Compiling wgpu-types v0.6.0 (https://github.com/gfx-rs/wgpu?rev=4ebe1f50b057046e4d4f015eb006330d62f5fe91#4ebe1f50)
error[E0658]: `match` is not allowed in a `const fn`
    --> /home/managor/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/4ebe1f5/wgpu-types/src/lib.rs:1594:9
     |
1594 | /         match self {
1595 | |             Self::Uchar2 | Self::Char2 | Self::Uchar2Norm | Self::Char2Norm => 2,
1596 | |             Self::Uchar4
1597 | |             | Self::Char4
...    |
1617 | |             Self::Float4 | Self::Uint4 | Self::Int4 => 16,
1618 | |         }
     | |_________^
     |
     = note: for more information, see https://github.com/rust-lang/rust/issues/49146

error: aborting due to previous error
```

**Repro steps**
Try to makepkg the ruffle package from AUR

**Expected vs observed behavior**
The compiler should be able to compile wgpu

**Platform**
Arch Linux

**Comment by cwfitzgerald** [comment] 2021-01-05 12:50
Thank you for filing!

This is because the version of rust being used to compile is less than 1.46. Wgpu requires that at least version rustc 1.46. We need to more formally define our MSRV, but that is the current state of things.

If you think the MSRV should be changed, then discuss on #780. I'm going to close this as a duplicate of #780.

**Closed by cwfitzgerald** 2021-01-05 12:50 UTC
