### ISSUE TITLE
can't return array anymore

### ISSUE THREAD

**Issue by mikeny07** [gfx-rs/wgpu#3912] opened 2023-07-07 16:21 UTC
**Description**

I have a WGSL shader function and the simplified version like this:

fn myfunc() -> array<vec3<f32>, 4>{
    return array<vec3<f32>, 4>(
        vec3<f32>(0.0,0.0,0.51),
        vec3<f32>(0.0,0.24,0.67),
        vec3<f32>(0.01,0.49,0.78),
        vec3<f32>(0.01,0.75,0.89),
    );
}

This function works fine in wgpu version 0.11, and also works in latest WebGPU 0.1.34. However, when updating to wgpu 0.16, this function gives error:

Internal error: FXC D3DCompile error (0x80004005): C:\Shader(58,5-254): error X3017: cannot convert from 'const typedef float3[4]' to 'float3'.

**Platform**
Windows 11, RTX 3060, backend: DX12.

**Comment by teoxoy** [comment] 2023-07-07 16:51
Closing as duplicate of https://github.com/gfx-rs/wgpu/issues/4393.

**Closed as not planned by teoxoy** 2023-07-07 16:51 UTC

**Comment by mikeny07** [comment] 2023-07-07 17:55
[gfx-rs/wgpu#4393](https://github.com/gfx-rs/wgpu/issues/4393) does not fix my problem. My question is why this code runs in wgpu 0.11 and doesn't run in wgpu 0.16. What change needs to be made to this function in order for it to run in wgpu 0.16

**Comment by teoxoy** [comment] 2023-07-07 19:25
You were most likely using a different backend before.

I just looked at the diff between the current release and naga v0.7 and the code that is causing the issue has not been changed.

I also checked the output of the hlsl backend and it still has the error.

**Comment by mikeny07** [comment] 2023-07-07 20:33
You are right, when switching back to the Vulkan backend, the function works. Don't know why DX12 not working...

**Comment by teoxoy** [comment] 2023-07-07 21:04
We are generating wrong code, that is tracked by https://github.com/gfx-rs/wgpu/issues/4393.

**Comment by cwfitzgerald** [comment] 2023-07-07 21:51
If you want to work around this, use an out pointer in the function argument `ptr<function, array<vec3, 4>>`. It's clunky, but works.
