### ISSUE TITLE
hello-triangle panics on minimize

### ISSUE THREAD

**Issue by branpk** [gfx-rs/wgpu#1523] opened 2021-06-19 17:39 UTC
**Description**
The hello-triangle example panics after minimizing the window, with the following stack trace:

```
thread 'main' panicked at 'Index 0 is already occupied', wgpu\wgpu-core\src\hub
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/16e18395ce33ca1ebfe60a591fb2f9317a75d822\/library\std\src\panicking.rs:515
   1: std::panicking::begin_panic_fmt
             at /rustc/16e18395ce33ca1ebfe60a591fb2f9317a75d822\/library\std\src\panicking.rs:457
   2: wgpu_core::hub::Storage<wgpu_core::swap_chain::SwapChain<wgpu_hal::vulkan::Api>, wgpu_core::idswap_chain::SwapChain<wgpu_hal::empty::Api>>>::insert_impl<wgpu_core::swap_chain::SwapChain<wgpu_halgpu_core::id::Id<wgpu_core::s
             at .\wgpu-core\src\hub.rs:162
   3: wgpu_core::hub::Storage<wgpu_core::swap_chain::SwapChain<wgpu_hal::vulkan::Api>, wgpu_core::idswap_chain::SwapChain<wgpu_hal::empty::Api>>>::insert_error<wgpu_core::swap_chain::SwapChain<wgpu_hawgpu_core::id::Id<wgpu_core::
             at .\wgpu-core\src\hub.rs:173
   4: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_swap_chain<wgpu_ityManagerFactory,wgpu_hal::vulkan::Api>
             at .\wgpu-core\src\device\mod.rs:4153
   5: wgpu::backend::direct::{{impl}}::device_create_swap_chain
             at .\wgpu\src\backend\direct.rs:796
   6: wgpu::Device::create_swap_chain
             at .\wgpu\src\lib.rs:1673
   7: hello_triangle::run::{{closure}}::{{closure}}
             at .\wgpu\examples\hello-triangle\main.rs:91
```

The other examples don't panic, since they use `.max(1)` before creating the swap chain.

I've seen a few issues that were closed as a dupe of #1026, but this still seems to be present.

**Repro steps**
Check out latest master, run hello-triangle example.

**Expected vs observed behavior**
I would expect either:
* Ideally, creating a zero sized swap chain just works. I know not all back ends support it, but maybe it could be implemented within wgpu.
* Creating a zero sized swap chain produces a meaningful error message, and the hello-triangle example is updated to use `.max(1)`.

**Platform**

* Windows 10
* `AdapterInfo { name: "GeForce GTX 1080 Ti", vendor: 4318, device: 6918, device_type: DiscreteGpu, backend: Vulkan }`
* Latest wgpu master
* winit 0.24.0

**Comment by Craig-Macomber** [comment] 2021-07-19 20:27
This does not reproduce on Linux with X11 on Latest wgpu master with winit 0.24.0 on vulkan.
Looks like my window manager does not resize on minimize, and manual window sizing bottoms out at 1x29.

However if I force the size to 0 by 0, I get the same panic as in this issue: "'Index 0 is already occupied', /.../wgpu/wgpu-core/src/hub.rs:172:18"

Therefor I think the repro listed in this issue is not portable, but the issue itself seems to be a general one (bad error message for 0 by 0 swap chains)

**Comment by Craig-Macomber** [comment] 2021-07-19 20:30
Looking at #1100 it seems like that validation is not working: I do not get the nice error text that commit adds.

**Comment by cwfitzgerald** [comment] 2023-10-14 03:01
Closing as out of date, this should be fixed.

**Closed by cwfitzgerald** 2023-10-14 03:01 UTC
Labels: type: bug, help wanted, area: validation, api: vulkan
