### ISSUE TITLE
DX12's `max_storage_textures_per_shader_stage` is set too low

### ISSUE THREAD

**Issue by Elabajaba** [gfx-rs/wgpu#3784] opened 2023-05-19 04:36 UTC
**Description**
`wgpu::Limits::max_storage_textures_per_shader_stage` for DX12 is set to 4, when it should be at least 8, and higher on most hardware.

**Extra materials**
https://learn.microsoft.com/en-us/windows/win32/direct3d12/hardware-support

**Platform**
DX12

**Comment by cwfitzgerald** [comment] 2023-05-19 04:38
We can assume FL11_1 for WebGPU purposes. So this can be set to `64 / 2 shader stages / 2 types of UAVs` = 16 for both `max_storage_textures_per_shader_stage` and `max_storage_buffers_per_shader_stage`

**Comment by cwfitzgerald** [comment] 2023-05-19 04:40
Actually this is a duplicate of #3333

**Closed as not planned by cwfitzgerald** 2023-05-19 04:40 UTC
