### ISSUE TITLE
Memory Leak in Command Buffer

### ISSUE THREAD

**Issue by skyline131313** [gfx-rs/wgpu#2562] opened 2022-03-28 20:20 UTC
**Description**
Memory leak cause by command buffer being stored into a list, but doesn't appear to ever be used.
See: https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/command/mod.rs#L56
Created in wgpu-hal: https://github.com/gfx-rs/wgpu/blob/master/wgpu-hal/src/vulkan/command.rs#L49

**Repro steps**
Just using the most basic example, whenever a command is issued, memory is cached for later but never re-used.

**Expected vs observed behavior**
Expected: re-use command buffer or destroy it.
Observed: command buffer is kept in a list and the list just grows indefinitely.

**Extra materials**

See also: https://github.com/gfx-rs/wgpu-native/issues/182

Call stack of the leak:
```
Error #2166: POSSIBLE LEAK 25023 direct bytes 0x0000011967515340-0x000001196751b4ff + 0 indirect bytes
# 0 replace_RtlAllocateHeap                                                    [d:\a\drmemory\drmemory\common\alloc_replace.c:3772]
# 1 amdvlk64.dll!vk_icdGetInstanceProcAddrSG                                  +0xa1c10f (0x0000011952b3c2f0 <amdvlk64.dll+0xaac2f0>)
# 2 amdvlk64.dll!vk_icdGetInstanceProcAddrSG                                  +0x9fee34 (0x0000011952b1f015 <amdvlk64.dll+0xa8f015>)
# 3 amdvlk64.dll!vk_icdNegotiateLoaderICDInterfaceVersion                     +0x1846f  (0x00000119520b62b0 <amdvlk64.dll+0x262b0>)
# 4 VkLayer_khronos_validation.dll!DispatchAllocateCommandBuffers              [c:\j\msdk\build\vulkan-validationlayers\repo\layers\generated\layer_chassis_dispatch.cpp:1215]
# 5 VkLayer_khronos_validation.dll!vulkan_layer_chassis::AllocateCommandBuffers [c:\j\msdk\build\vulkan-validationlayers\repo\layers\generated\chassis.cpp:2629]
# 6 vulkan-1.dll!vkDestroyDescriptorPool                                      +0x2fd14  (0x00007ffee4b3ce65 <vulkan-1.dll+0x3ce65>)
# 7 wgpu_native.dll!ash::vk::features::DeviceFnV1_0::allocate_command_buffers  [C:\Users\mk\.cargo\registry\src\github.com-1ecc6299db9ec823\ash-0.33.3+1.2.191\src\vk\features.rs:4520]
# 8 wgpu_native.dll!ash::device::Device::allocate_command_buffers              [C:\Users\mk\.cargo\registry\src\github.com-1ecc6299db9ec823\ash-0.33.3+1.2.191\src\device.rs:1903]
# 9 wgpu_native.dll!wgpu_hal::vulkan::command::impl$2::begin_encoding          [C:\Users\mk\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\ec1d022\wgpu-hal\src\vulkan\command.rs:54]
#10 wgpu_native.dll!wgpu_core::command::CommandEncoder<>::open_pass<>          [C:\Users\mk\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\ec1d022\wgpu-core\src\command\mod.rs:81]
#11 wgpu_native.dll!wgpu_core::hub::Global<>::command_encoder_run_render_pass_impl<> [C:\Users\mk\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\ec1d022\wgpu-core\src\command\render.rs:1037]
#12 wgpu_native.dll!wgpu_core::hub::Global<>::command_encoder_run_render_pass<> [C:\Users\mk\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\ec1d022\wgpu-core\src\command\render.rs:994]
#13 wgpu_native.dll!wgpu_native::command::wgpuRenderPassEncoderEnd             [C:\src\wgpu-native\src\command.rs:164]
```

**Platform**
Windows x64, with master branch of gpu_native. I think at least wgpu v0.11.2.

**Comment by cwfitzgerald** [comment] 2022-03-28 20:25
Thanks for filing and figuring it out! Seems to be a dupe of #2553; we should figure out what's going on here.

**Closed by cwfitzgerald** 2022-03-28 20:25 UTC

**Comment by kvark** [comment] 2022-03-29 06:21
Reusing command buffers is a very basic thing. Without it, all of our infra would instantly fall apart, since DX12 (in particular) is very memory-hungry for command buffers. Making sure that we are re-using them properly (internally) was one of the first major things set up in wgpu-hal. So I'd be very surprised if it broke, somehow. I'd be less surprised if something wonky is going on, e.g. the command buffers are recorded with an error, and therefore the common path is not taken, and some logic is confused.
