### ISSUE TITLE
Enable DX12 GPU Based Validation

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#4291] opened 2023-10-24 05:03 UTC
We are missing additional potential validation from d3d by not using GPU based validation.

See https://learn.microsoft.com/en-us/windows/win32/api/d3d12sdklayers/nf-d3d12sdklayers-id3d12debug3-setenablegpubasedvalidation

**Comment by jimblandy** [comment] 2024-01-11 15:12
https://learn.microsoft.com/en-us/windows/win32/direct3d12/using-d3d12-debug-layer-gpu-based-validation

**Comment by jimblandy** [comment] 2024-01-11 15:13
> The patched shaders inspect root arguments and resources accessed during shader execution and report errors to a log buffer.

**Comment by teoxoy** [comment] 2024-01-11 15:13
Closing as dupe of https://github.com/gfx-rs/wgpu/issues/1709.

**Closed as not planned by teoxoy** 2024-01-11 15:13 UTC
Labels: type: enhancement, backend: dx12, area: tests
