### ISSUE TITLE
Two versions of wgpu in the dependency tree cause a link error

### ISSUE THREAD

**Issue by kamirr** [gfx-rs/wgpu#3531] opened 2023-02-26 11:01 UTC
**Description**
Having two distinct version of `wgpu` in the dependency tree causes link errors related to multiple definitions of symbols, such as:
```
/home/REDACTED/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.14.2/src/command/render.rs:2447: multiple definition of `wgpu_render_pass_execute_bundles'; /home/REDACTED/wgpu-issue-repro/target/debug/deps/libwgpu_core-8230a6325f285aeb.rlib(wgpu_core-8230a6325f285aeb.wgpu_core.fe0e7c91-cgu.9.rcgu.o):/home/REDACTED/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.15.1/src/command/render.rs:2495: first defined here
```

I assume this is due to `#[no_mangle]` attributes on `wgpu-core` functions.

**Repro steps**
[wgpu-issue-repro.zip](https://github.com/gfx-rs/wgpu/files/10833501/wgpu-issue-repro.zip)
simply run `cargo build`. The example includes bevy 0.9.1 (which in turn includes wgpu 0.14) as well as wgpu 0.15. The source contains a minimal use of both libraries so that dead-code elimination doesn't hide the issue of duplicate symbols.

**Expected vs observed behavior**
Code should buil, it doesn't.

**Extra materials**
n/a

**Platform**
Ubuntu 22.04

**Comment by kamirr** [comment] 2023-02-26 11:05
If this use-case is to be supported, perhaps disabling `#[no_mangle]` for Rust-only builds (or via some feature-flag, if this would be infeasible to detect) would be the way to go?

**Comment by cwfitzgerald** [comment] 2023-02-27 06:17
Dupe of https://github.com/gfx-rs/wgpu/issues/3105 which has some more context - this is a fix we want to implement, just needs ff's goahead.

**Closed by cwfitzgerald** 2023-02-27 06:17 UTC
