### ISSUE TITLE
Is it possible to convert textures & buffers to/from backend handle types?

### ISSUE THREAD

**Issue by Gonkalbell** [gfx-rs/wgpu#1460] opened 2020-08-27 17:32 UTC
If I'm only concerned about a single backend, and I am using and API that directly returns/uses raw handles to OpenGL/Vulkan objects, is there a way to convert those handles to/from their corresponding wgpu object? I don't seem to see any way to currently do this in wgpu-rs, wgpu-native, or gfx-hal, but I could have missed something. If it's not a feature yet, is there any plan to add it?

**Comment by cwfitzgerald** [comment] 2022-06-05 21:50
Duplicate of #965.

**Closed by cwfitzgerald** 2022-06-05 21:50 UTC
Labels: type: enhancement, help wanted, area: api
