### ISSUE TITLE
Boids Fails Validation on MoltenVK

### ISSUE THREAD

**Issue by jinleili** [gfx-rs/wgpu#2774] opened 2022-06-15 02:46 UTC
**Repro steps**
Running the test suite:
```sh
WGPU_BACKEND=vk cargo nextest run --features vulkan-portability -- --example boids  --no-fail-fast
```
Output failure message：
```sh
--- STDERR:                            wgpu::example/boids boids ---
[2022-06-15T02:20:02Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-vkResetCommandPool-commandPool-00040 (0xb53e2331)]
    Validation Error: [ VUID-vkResetCommandPool-commandPool-00040 ] Object 0: handle = 0x600001744eb8, name = (wgpu internal) Transit, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xb53e2331 | Attempt to reset command pool with VkCommandBuffer 0x600001744eb8[(wgpu internal) Transit] which is in use. The Vulkan spec states: All VkCommandBuffer objects allocated from commandPool must not be in the pending state (https://vulkan.lunarg.com/doc/view/1.3.204.1/mac/1.3-extensions/vkspec.html#VUID-vkResetCommandPool-commandPool-00040)
[2022-06-15T02:20:02Z ERROR wgpu_hal::vulkan::instance] objects: (type: COMMAND_BUFFER, hndl: 0x600001744eb8, name: (wgpu internal) Transit)
[2022-06-15T02:20:02Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-vkResetCommandPool-commandPool-00040 (0xb53e2331)]
    Validation Error: [ VUID-vkResetCommandPool-commandPool-00040 ] Object 0: handle = 0x600001744f88, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xb53e2331 | Attempt to reset command pool with VkCommandBuffer 0x600001744f88[] which is in use. The Vulkan spec states: All VkCommandBuffer objects allocated from commandPool must not be in the pending state (https://vulkan.lunarg.com/doc/view/1.3.204.1/mac/1.3-extensions/vkspec.html#VUID-vkResetCommandPool-commandPool-00040)
[2022-06-15T02:20:02Z ERROR wgpu_hal::vulkan::instance] objects: (type: COMMAND_BUFFER, hndl: 0x600001744f88, name: ?)
[2022-06-15T02:20:02Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-vkDestroyBuffer-buffer-00922 (0xe4549c11)]
    Validation Error: [ VUID-vkDestroyBuffer-buffer-00922 ] Object 0: handle = 0x967dd1000000000e, name = (wgpu internal) initializing unmappable buffer, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xe4549c11 | Cannot free VkBuffer 0x967dd1000000000e[(wgpu internal) initializing unmappable buffer] that is in use by a command buffer. The Vulkan spec states: All submitted commands that refer to buffer, either directly or via a VkBufferView, must have completed execution (https://vulkan.lunarg.com/doc/view/1.3.204.1/mac/1.3-extensions/vkspec.html#VUID-vkDestroyBuffer-buffer-00922)
[2022-06-15T02:20:02Z ERROR wgpu_hal::vulkan::instance] objects: (type: BUFFER, hndl: 0x967dd1000000000e, name: (wgpu internal) initializing unmappable buffer)
[2022-06-15T02:20:02Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-vkDestroyBuffer-buffer-00922 (0xe4549c11)]
    Validation Error: [ VUID-vkDestroyBuffer-buffer-00922 ] Object 0: handle = 0x95a125000000001a, name = (wgpu internal) initializing unmappable buffer, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xe4549c11 | Cannot free VkBuffer 0x95a125000000001a[(wgpu internal) initializing unmappable buffer] that is in use by a command buffer. The Vulkan spec states: All submitted commands that refer to buffer, either directly or via a VkBufferView, must have completed execution (https://vulkan.lunarg.com/doc/view/1.3.204.1/mac/1.3-extensions/vkspec.html#VUID-vkDestroyBuffer-buffer-00922)
```

**Platform**
M1 Mac, Vulkan SDK (1.3.204.1)

**Comment by teoxoy** [comment] 2024-07-26 10:48
Judging by the "(wgpu internal) Transit"/"(wgpu internal) initializing unmappable buffer" labels I think this was fixed by 61739d95833b8217452a5f77455f2ab03eff649e (https://github.com/gfx-rs/wgpu/pull/5910).

There is still an instance where this example runs into early resource destruction https://github.com/gfx-rs/wgpu/pull/5964#issuecomment-2233875589 which is caused by https://github.com/gfx-rs/wgpu/issues/3601.

**Closed by teoxoy** 2024-07-26 10:48 UTC
Labels: type: bug, area: correctness, api: vulkan
