### ISSUE TITLE
Update raw-window-handle to 0.5.0

### ISSUE THREAD

**Issue by aleokdev** [gfx-rs/wgpu#2933] opened 2022-08-01 17:49 UTC
Please update the dependency on raw-window-handle to latest 0.5.0.

**Comment by CatCode79** [comment] 2022-08-01 17:57
The team and contributors to the project are almost there:
https://github.com/gfx-rs/wgpu/pull/2918

**Comment by cwfitzgerald** [comment] 2022-08-01 17:59
Duplicate of #2928 - note that this can't go out as a patch release as it's a public dependency - so this will need to wait until 0.14 in late september. In the mean time, you can use a git dependency once that PR merges.

**Closed by cwfitzgerald** 2022-08-01 17:59 UTC

**Comment by aleokdev** [comment] 2022-08-01 18:07
Thanks and sorry, didn't see those!
