### ISSUE TITLE
Submitting compute pipelines without polling causes high memory use and device disconnection

### ISSUE THREAD

**Issue by kurtschelfthout** [gfx-rs/wgpu#3806] opened 2023-05-27 13:14 UTC
**Description**
As far as I can tell, a very simple, single-threaded shader with a loop of more than 256 * 256 iterations (not an exact bound) that reuses a single compute pipeline, causes very high shared GPU memory usage if you repeat run the same shader over and over. Ultimately, I run out of shared memory and get a device disconnection.

This most reliable replicates with the DX12 backend, and in fact my repro only reliably works with that backend on my machine, but in my "real" program I have seen similar behavior in benchmarks with Vulkan, where it also blows up dedicated GPU memory.  Sorry to be a bit handwavy, I'm new to GPU programming and this is as far as I got!

**Repro steps**
Full code in this gist: https://gist.github.com/kurtschelfthout/d90006ab590686e71ce4092eb8a7f0c8

The rust code is just create a compute pipeline 101, then just runs the shader over and over. Note the input buffer is always reused, and the output buffer is a single float. So that I get +- 8GB of shared GPU memory usage in less than a minute of running this is strange to say the least.

The salient parts are this:

```wgsl
    for (var rec_i = 0u; rec_i < 512u * 512u; rec_i += 1u) {
```
If this is less, like `rec_j < 64`, I don't see the memory usage go up.

And if you put creation of the compute pipeline inside the loop, like this:

```rust
    for _ in 0..10000 {
        let compute_pipeline = pipeline(&device);
```
There is also no problem.

I need to run this with the DX12 backend:

```
WGPU_POWER_PREF="high"
WGPU_BACKEND = "DX12"
WGPU_ADAPTER_NAME = "NVIDIA"
```
Although as I said earlier, I saw the behavior also in benchmarks with Vulkan backend, which led me to investigate in the first place. Either way it is much more pronounced in the DX12 backend.

**Expected vs observed behavior**
I just expect the shader to run in constant memory. Instead it uses more and more memory and eventually causes a panic and device disconnect.

**Extra materials**
Screenshot of memory usage while running the repro. 

![image](https://github.com/gfx-rs/wgpu/assets/164917/97bc2022-17a6-4199-bab9-6079ecdac1d2)

If I run 10x more iterations in `main`, I get this:

![image](https://github.com/gfx-rs/wgpu/assets/164917/8e3b5930-976c-4b9f-a545-7198bf470922)

GPU utilization is 100% the whole time.

If I keep running, it eventually blows up.

**Platform**
Windows 10, wgpu 0.16, NVIDIA GeForce RTX 2070 with Max-Q Design, Dx12 backend

**Comment by Wumpf** [comment] 2023-05-27 17:26
I haven't dived deep into your code, but from a first glimpse it looks like the problem is that you schedule a lot of compute jobs but never actually wait for them to finish. Meaning you get a very large number of command buffers in flight that use up all the memory.
Try and see what happens if you call [`device.poll`](https://docs.rs/wgpu/latest/wgpu/struct.Device.html#method.poll) `Maintain::Wait` after a few `submit` calls, or even better make sure that there is a fixed number in flight by using `Maintain::WaitForSubmissionIndex`.

Tbh I'm not sure how this is supposed to play out with a WebGPU target where `device.poll` is a no-op (it does not exist in the WebGPU spec), I think browsers will internally block `submit` if there's too much in flight. But afaik wgpu-core doesn't do that

**Comment by jimblandy** [comment] 2023-05-27 18:17
> Tbh I'm not sure how this is supposed to play out with a WebGPU target where `device.poll` is a no-op (it does not exist in the WebGPU spec), I think browsers will internally block `submit` if there's too much in flight. But afaik wgpu-core doesn't do that

In Firefox, at the moment, we just have a timer job that calls maintain periodically. We'll probably change that to run as part of the other per-frame processing.

**Comment by kurtschelfthout** [comment] 2023-05-27 20:01
@Wumpf nice, thanks yes `poll` totally solves the memory usage. And is also a bug in my original program - I hadn't taken into account that the GPU can be executing multiple dispatches concurrently.

Some observations fwiw:

- Are you expecting this kind of memory usage even without poll? Unless I'm misunderstanding something, my code allocates a single buffer of 1MiB, and then 10,000x a buffer of 4 bytes, for a total of 39KiB. I understand the command buffer etc takes memory too, but I'm looking at 3~4GiB, which seems orders of magnitude off.
- Perhaps it's worth dealing with this problem more explicitly in wgpu somehow? Would be nice to either have a nicer error message that points to the problem, or some kind of "back pressure" like blocking on `submit` as you suggest. Not sure if appropriate.

Anyway just a few thoughts...happy to close if you folks feel like this is just user error.

**Comment by Wumpf** [comment] 2023-05-29 07:21
> Are you expecting this kind of memory usage even without poll? 

It would definitely be interesting to dig into and see why it is that bad, but that's not even that easy: The memory usage is on the GPU side so it could be that the driver allocates quite large fixed chunks for each command buffer that is tallied in the GPU memory. Wgpu should not cause much memory overhead other than that for what you're doing, it would be nice though to confirm that.


> Perhaps it's worth dealing with this problem more explicitly in wgpu somehow? 

It should be fairly easy to add a warning if there's "clearly" too many things in flight on the queue, maybe it could log a warning above 100 command buffers or so 🤔

**Comment by kurtschelfthout** [comment] 2023-05-29 08:24
> The memory usage is on the GPU side so it could be that the driver allocates quite large fixed chunks for each command buffer that is tallied in the GPU memory. 

Indeed, that does seem to be the case - different backends have different behaviors here. DX12 is pretty easy to trigger high memory usage, Vulkan seems much better.

**Comment by jimblandy** [comment] 2024-07-03 15:47
It seems like the original issue has been addressed, and we don't have a bug that needs to be fixed here, so I'm going to close this. If something comes up, feel free to re-open.

**Closed as not planned by jimblandy** 2024-07-03 15:47 UTC
