### ISSUE TITLE
15.1 Bug - `assertion failed: wasm.is_instance_of::<T>()`

### ISSUE THREAD

**Issue by simbleau** [gfx-rs/wgpu#3481] opened 2023-02-11 20:35 UTC
https://github.com/gfx-rs/wgpu/blob/bb01d723ba90654fdec85d931edbe7c9be56869e/wgpu/src/backend/web.rs#L53

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/48108917/218280018-06ebf672-b76f-4688-a138-9e4a5355a2fb.png">

**Comment by simbleau** [comment] 2023-02-11 20:46
Sorry for the limited context, here's a longer thread: https://github.com/linebender/vello/issues/276

**Comment by cwfitzgerald** [comment] 2023-02-11 22:12
Duplicate of #3430

**Closed by cwfitzgerald** 2023-02-11 22:12 UTC
