### ISSUE TITLE
naga: Miscompilation with "break if"

### ISSUE THREAD

**Issue by Patryk27** [gfx-rs/wgpu#4982] opened 2024-01-04 11:02 UTC
Hi, this wgsl:

```wgsl
fn main() -> u32 {
  var counter = 0u;

  loop {
    counter += 1u;

    continuing {
      break if counter == 5u;
    }
  }

  return counter;
}
```

... gets compiled into this Metal:

```metal
// language: metal1.0
#include <metal_stdlib>
#include <simd/simd.h>

using metal::uint;


uint main_(
) {
    uint counter = 0u;
    uint _e5 = counter;
    bool loop_init = true;
    while(true) {
        if (!loop_init) {
            if (_e5 == 5u) {
                break;
            }
        }
        loop_init = false;
        uint _e3 = counter;
        counter = _e3 + 1u;
    }
    uint _e8 = counter;
    return _e8;
}
```

I'm specifically wondering about the `_e5 == 5u` comparison there - shouldn't the code either refer to `counter` or update `_e5` somewhere? Currently it looks like the comparison would always yell `false`.

(I might be also misunderstanding how `break if` is supposed to work, though!)

**Comment by Patryk27** [comment] 2024-01-04 11:14
I'm not 100% sure, but seems to be the same case as https://github.com/gfx-rs/wgpu/issues/4558 (?)

**Comment by Patryk27** [comment] 2024-01-04 11:25
btw, even just going wgsl->wgsl yields funky results:
```wgsl
fn main() -> u32 {
    var counter: u32 = 0u;

    let _e5 = counter;
    loop {
        let _e3 = counter;
        counter = (_e3 + 1u);
        continuing {
            break if (_e5 == 5u);
        }
    }
    let _e8 = counter;
    return _e8;
}
```

**Comment by Patryk27** [comment] 2024-01-04 11:30
I think the block given to `break_if` here is wrong:

https://github.com/gfx-rs/wgpu/blob/7c21e605fbcc4160d6782d56c74fba9cbe1cb455/naga/src/front/wgsl/lower/mod.rs#L1330

Shouldn't it say this, considering that `break if` is part of the `continuing` block?

```rust
                let break_if = break_if
                    .map(|expr| {
                        self.expression(expr, &mut ctx.as_expression(&mut continuing, &mut emitter))
                    })
                    .transpose()?;
```

**Comment by Patryk27** [comment] 2024-01-04 11:33
This also seems to solve https://github.com/gfx-rs/wgpu/issues/4558, but I've gotta test it more.

Edit: it solves the issue when going wgsl->msl, but spv->msl is still generated wrong, then.

**Comment by teoxoy** [comment] 2024-01-05 12:48
> I think the block given to `break_if` here is wrong:
> 
> https://github.com/gfx-rs/wgpu/blob/7c21e605fbcc4160d6782d56c74fba9cbe1cb455/naga/src/front/wgsl/lower/mod.rs#L1330
> 
> Shouldn't it say this, considering that `break if` is part of the `continuing` block?
> 
> ```rust
>                 let break_if = break_if
>                     .map(|expr| {
>                         self.expression(expr, &mut ctx.as_expression(&mut continuing, &mut emitter))
>                     })
>                     .transpose()?;
> ```

That does look wrong indeed. Could you open a PR?

I think https://github.com/gfx-rs/wgpu/issues/4558 is a duplicate of this as well.

**Closed as completed** 2024-01-08 09:50 UTC
Labels: type: bug, naga, area: naga front-end, lang: WGSL
