### ISSUE TITLE
Some buffer memory does not get freed after the device is dropped

### ISSUE THREAD

**Issue by cryscan** [gfx-rs/wgpu#5648] opened 2024-05-02 08:38 UTC
**Description**
Some buffer memory not get freed after the device is dropped.
![40d0847837d2d92e9c1cd014f5ed97a4](https://github.com/gfx-rs/wgpu/assets/16053640/c6cefcd3-019a-4638-be59-8085af38b13c)

In the picture above, I load the same amount of data twice. Between the loads I drop the adapter, the device and all the buffers. However it seems that there are still some GPU memory not freed.

**Expected vs observed behavior**
- Expected: The two loads take the same amount of GPU memory.
- Observed: The later load takes more memory, and if repeating the process you will get an OOM.

**Platform**
```
AdapterInfo {
    name: "AMD Radeon 780M Graphics",
    vendor: 4098,
    device: 5567,
    device_type: IntegratedGpu,
    driver: "AMD proprietary driver",
    driver_info: "22.40.05.11 (LLPC)",
    backend: Vulkan,
}
```

**Comment by cryscan** [comment] 2024-05-02 08:48
Maybe related to #3518 and #3498?

**Comment by cryscan** [comment] 2024-05-02 17:05
Update: Tried
```rust
queue.submit(None);
device.poll(Maintain::Wait);
```
before dropping, it gets mitigated, but each reload still adds 0.2GB.

**Comment by jimblandy** [comment] 2024-05-13 16:42
@cryscan Thanks for the bug report and the analysis!

Do the issues you linked (#3518, #3498) exhibit the same behavior on your system? It is extremely valuable for us to have a test case that can reproduce the issue.

**Comment by teoxoy** [comment] 2024-07-31 15:40
This is most likely a duplicate of https://github.com/gfx-rs/wgpu/issues/3498 or https://github.com/gfx-rs/wgpu/issues/5529 (which have been fixed).

If you are still seeing leaks like this on the latest release (v22) please reopen the issue or create a new one with a minimum reproducible example.

**Closed as not planned by teoxoy** 2024-07-31 15:40 UTC
