### ISSUE TITLE
WGPU Target view and swap chain errors.

### ISSUE THREAD

**Issue by genusistimelord** [gfx-rs/wgpu#5384] opened 2024-03-13 18:55 UTC
**Description**
when running the project with Backends::PRIMARY or Backends::ALL I get the following Errors in my log output.

```
WARN - InstanceFlags::VALIDATION requested, but unable to find layer: VK_LAYER_KHRONOS_validation
INFO - Debug utils not enabled: debug_utils_user_data not passed to Instance::from_raw
INFO - Adapter Vulkan AdapterInfo { name: "AMD Radeon RX 7900 XT", vendor: 4098, device: 29772, device_type: DiscreteGpu, driver: "AMD proprietary driver", driver_info: "24.2.1 (LLPC)", backend: Vulkan }
ERROR - ID3D12CommandQueue::ExecuteCommandLists: Using ClearRenderTargetView on Command List (0x000001E6E421D610:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0x38975C90: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x000001E6E3DBAA10:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0x38975C70: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0x38975C50: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
ERROR - ID3D12CommandQueue::ExecuteCommandLists: Using IDXGISwapChain::Present on Command List (0x000001E6C3206DA0:'Internal DXGI CommandList'): Resource state (0x389760C0: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x000001E6E3DBAA10:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a PRESENT_SOURCE.  Expected State Bits (all): 0x389760A0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Actual State: 0x38976080: D3D12_RESOURCE_STATE_RENDER_TARGET, Missing State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]

```
**Repro steps**
This only appears when i attempt to run the EXE on its own with logging enabled. If i run it in debug mode or even with RenderDocs the error does not occur. If i manually set the Backends to Vulkan, DX12 or Opengl and run the exe it also does not output these errors. Even with the Errors above everything renders correctly. Also i do notice if i set the instance flags to 
flags: InstanceFlags::empty(), it does not display this error. I am curious as to what this error means and if it even is a valid error.

**Expected vs observed behavior**
would expect these errors to not occur.

**Platform**
Windows 11

**Comment by cwfitzgerald** [comment] 2024-03-13 23:33
Closing as duplicate of #4247 - it's an issue with how AMD does swapchain layering that we're picking up due to how we listen for logs.

**Closed as not planned by cwfitzgerald** 2024-03-13 23:33 UTC
