### ISSUE TITLE
`sampleTextureLevel(t: texture_depth_2d, ...)` enforces wrong level argument type

### ISSUE THREAD

**Issue by cshenton-work** [gfx-rs/wgpu#5127] opened 2024-01-23 22:01 UTC
**Description**

Naga errors out on a shader invoking `sampleTextureLevel` on a `texture_depth_2d` if you pass an integer argument.

![image](https://github.com/gfx-rs/wgpu/assets/151570269/5c9bda2e-6304-48e9-93e9-6657c733dbe1)

However the spec specifies that this argument _must_ be an integer. So Naga is enforcing incorrect semantics here.

![image](https://github.com/gfx-rs/wgpu/assets/151570269/1665d825-cd10-4143-be37-64607ba161bc)

So if you _do_ pass a float it will then fail validation on chromium, which implements the spec correctly:

<img width="646" alt="image" src="https://github.com/gfx-rs/wgpu/assets/151570269/a442c57c-bc99-4e64-8596-5ee1f3c7cccf">

**Repro steps**
Call `sampleTextureLevel(texture_depth_2d, sampler, vec2f, u32)` from a shader (I am calling it from compute, which is why I must use sampleLeve) on the WebGPU Browser backend.

**Platform**
Chrome, Windows 11

**Comment by cshenton-work** [comment] 2024-01-23 22:16
Is there a way to disable naga validation entirely on Browser WebGPU? This is quite a blocker for me and if naga's not implementing the spec it seems reasonable that I can just ignore its internal validation and pass whatever string I want to the browser's correct implementation.

**Comment by cwfitzgerald** [comment] 2024-01-23 22:25
We don't do any validation on the WebGPU backend - in fact naga isn't even compiled in.

**Comment by cshenton-work** [comment] 2024-01-23 22:26
So why might I be seeing a naga validation error in the chrome console?

**Comment by cshenton-work** [comment] 2024-01-23 22:33
Seems like Bevy is explicitly invoking naga in the browser :(

**Comment by cshenton-work** [comment] 2024-01-23 23:25
No actually the error comes from wgpu afaict. wgpu 0.18 does seem to validate on its web backend.

https://github.com/gfx-rs/wgpu/blob/v0.18/wgpu/src/backend/web.rs#L1467

**Comment by cwfitzgerald** [comment] 2024-01-24 02:07
This is a byproduct of how bevy is doing things, the line is question is the path for when we're handed a Naga module as a shader - ofc in that case we need to validate it and translate to wgsl.

**Comment by cshenton-work** [comment] 2024-01-24 02:28
Ah I think I understand. So what is the correct codepath to interact with wgpu 0.18 to avoid validation on Browser WebGPU if I already have valid wgsl source that the browser can ingest directly?

**Comment by cwfitzgerald** [comment] 2024-01-24 03:07
As long as you're running down the wgsl shader source variant, we'll pass it directly through

**Comment by cshenton-work** [comment] 2024-01-24 03:11
I guess it's relying on Naga still to do things like resolves includes, and that opts it into validation no matter what.
I've found a workaround for now by calling textureGather instead, but ideally the validation behaves correctly and that won't be necessary.

**Comment by cwfitzgerald** [comment] 2024-01-24 03:19
Yup, this is still a bug on our end

**Comment by teoxoy** [comment] 2024-01-24 12:01
This is a duplicate of https://github.com/gfx-rs/wgpu/issues/4548.

**Closed as not planned by teoxoy** 2024-01-24 12:01 UTC
Labels: naga, area: naga front-end, lang: WGSL
