### ISSUE TITLE
 Internal error in ShaderStages

### ISSUE THREAD

**Issue by alexandrasp** [gfx-rs/wgpu#4884] opened 2023-12-16 03:15 UTC
I tried to build [Space Editor](https://github.com/rewin123/space_editor) and got this *wgpu* error. Do you have any ideas/suggestions/directions to fix it? 

```
2023-12-16T02:32:08.570721Z  INFO bevy_render::renderer: AdapterInfo { name: "Intel Iris Pro Graphics", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2023-12-16T02:32:09.399009Z  INFO bevy_xpbd_plugin: Add bevy_xpbd_3d plugin to editor
BevyXpbdPlugin::build
2023-12-16T02:32:09.685914Z  INFO bevy_winit::system: Creating new window "App" (0v0)
2023-12-16T02:32:09.944747Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 12.7.1 ", kernel: "21.6.0", cpu: "Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz", core_count: "4", memory: "16.0 GiB" }
2023-12-16T02:32:10.027637Z  INFO bevy_input::gamepad: Gamepad { id: 0 } Connected
2023-12-16T02:32:10.110476Z  WARN persistence: Persistence file not found at path editor.ron
2023-12-16T02:32:11.455278Z ERROR log: Shader translation error for stage ShaderStages(VERTEX | FRAGMENT): new_render_pipeline_state: "Compiler encountered an internal error"
2023-12-16T02:32:11.455599Z ERROR log: Please report it to https://github.com/gfx-rs/naga
2023-12-16T02:32:11.455713Z ERROR log: Handling wgpu errors as fatal by default
thread 'Compute Task Pool (1)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `alpha_blend_mesh_pipeline`
    Internal error in ShaderStages(VERTEX | FRAGMENT) shader: new_render_pipeline_state: "Compiler encountered an internal error"

', /Users/apereira/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/backend/direct.rs:3056:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
thread 'Compute Task Pool (3)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/apereira/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.12.1/src/pipelined_rendering.rs:145:45
```

**Comment by teoxoy** [comment] 2024-01-02 11:41
This is probably a duplicate of https://github.com/gfx-rs/wgpu/issues/4817.
Could you share the shader that causes this issue? See the issue above for instructions on getting the shader.

**Comment by cwfitzgerald** [comment] 2024-01-12 20:37
Closing in favor of that one.

**Closed as not planned by cwfitzgerald** 2024-01-12 20:37 UTC
