### ISSUE TITLE
[Metal/Intel] Shadow example rendering glitch

### ISSUE THREAD

**Issue by jasondavies** [gfx-rs/wgpu#103] opened 2019-03-12 20:30 UTC
macOS 10.14.3
MacBook Pro (Retina, Mid 2012)
NVIDIA GeForce GT 650M 1024 MB
rustc 1.35.0-nightly (e68bf8ae1 2019-03-11)
Latest wgpu master at time of writing (9f70c2e59ffcee99d6a47d431094e7486076f3c0)

`cargo run --release --bin shadow --features=metal`

I'd be happy to dig deeper but I'm not sure of the best place to start.

<img width="1013" alt="Screenshot 2019-03-12 at 20 28 26" src="https://user-images.githubusercontent.com/31223/54233720-6ef1bc80-4505-11e9-9135-48b4ff052362.png">

**Comment by kvark** [comment] 2019-03-12 20:38
Thanks for filing! On the first sight, it looks like a driver bug.
The way to investigate this would be to create an XCode project (with "external build system" type), just so that you can start the application from XCode and force-enable Metal validation. If no validation errors show up, then we need to take an XCode GPU capture and analyze it. Needless to say, I'm not seeing the problem on Intel, I'll check on AMD as well.

**Comment by jasondavies** [comment] 2019-03-12 20:55
Thanks.  I did as you suggested and ran with Metal validation enabled (this was on by default) but nothing appeared in the log.

If it is a driver issue I assume there's not much I can do about it?  Side-note: I have experimented with MoltenVK in the past but I'm not sure if this would affect anything.

Running a GPU capture, the issue seems to crop up right near the last call; the call just before this one looks fine (see below):

<img width="1134" alt="Screenshot 2019-03-12 at 20 54 08" src="https://user-images.githubusercontent.com/31223/54235410-16bcb980-4509-11e9-8fae-89cc54e96ad5.png">

**Comment by kvark** [comment] 2019-03-12 21:12
If metal validation finds something, you get a crash/breakpoint when running from XCode, so it's difficult to ignore :)

If we confirm this to be a driver issue, we can submit a bug to Apple. I've had some success in them addressing the issues.

> Running a GPU capture, the issue seems to crop up right near the last call; the call just before this one looks fine (see below):

That is interesting. The artifacts are visible on the result of more than one draw call.

Could you save the capture to disk and send it over to me by, say, Firefox Send? Please share the link in our [gitter](https://gitter.im/gfx-rs/webgpu) where we generally discuss things.

**Comment by jasondavies** [comment] 2019-03-12 23:25
In case it's relevant: under System Report the NVIDIA GeForce GT 650M shows `Metal: Supported, feature set macOS GPUFamily1 v4`.

**Comment by kvark** [comment] 2019-03-17 04:11
Filed bug 48911699 on Apple radar for this.

**Comment by parasyte** [comment] 2019-04-25 21:53
FWIW, I see the same behavior on macOS with the Intel chipset.

```
Intel Iris Pro:

  Chipset Model:	Intel Iris Pro
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x0d26
  Revision ID:	0x0008
  Metal:	Supported, feature set macOS GPUFamily1 v4
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2880 x 1800 Retina
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
```

**Comment by seivan** [comment] 2019-08-22 15:45
Yeah it happens on the motherboard GPU (Intel) not with the dedicated GPU, at least not with @jasondavies gpu (I got the same) 
The example runs with `PowerPreference::LowPower` which means it will probably run with the Intel one at least on [9f70c2e](https://github.com/gfx-rs/wgpu/commit/9f70c2e59ffcee99d6a47d431094e7486076f3c0)

So mention of `NVIDIA GeForce GT 650M 1024 MB` is wrong.

**Comment by parasyte** [comment] 2019-09-01 08:53
AFAICT, this example was broken on discreet GPUs (Radeon Pro 560 4 GB in my case; patching `framework.rs` to use `PowerPreference::HighPerformance`) by https://github.com/gfx-rs/wgpu-rs/pull/4 which suggests the culprit is somewhere in this range: https://github.com/gfx-rs/wgpu/compare/0edf927...dd61d12

When I bisected this, the bad commit was https://github.com/gfx-rs/wgpu/pull/172

I haven't tried to investigate further. It looks like something in `gfx-hal 0.1 -> 0.2` broke it, or possibly `gfx-backend-metal 0.1 -> 0.2`

|    |`LowPower`|`HighPerformance`|
|----|----|----|
|[`cd9b7b8`](https://github.com/gfx-rs/wgpu/commit/cd9b7b8606b65f984a7c2244f297542e0b9c161b)|<a href="https://user-images.githubusercontent.com/456942/64074031-b3f7df80-cc5a-11e9-9bb3-aab0cdc33ec7.png"><img width="300" alt="cd9b7b8 LowPower" src="https://user-images.githubusercontent.com/456942/64074031-b3f7df80-cc5a-11e9-9bb3-aab0cdc33ec7.png"></a>|<a href="https://user-images.githubusercontent.com/456942/64074042-c96d0980-cc5a-11e9-8c5f-15fc10ef1f20.png"><img width="300" alt="cd9b7b8 HighPerformance" src="https://user-images.githubusercontent.com/456942/64074042-c96d0980-cc5a-11e9-8c5f-15fc10ef1f20.png"></a>|
|[`965d242`](https://github.com/gfx-rs/wgpu/commit/965d24245c98976af920f1d2cff1be3de77c387a)|<a href="https://user-images.githubusercontent.com/456942/64074026-9e82b580-cc5a-11e9-933e-0055cb737e4f.png"><img width="300" alt="965d242 LowPower" src="https://user-images.githubusercontent.com/456942/64074026-9e82b580-cc5a-11e9-933e-0055cb737e4f.png"></a>|<a href="https://user-images.githubusercontent.com/456942/64073912-367f9f80-cc59-11e9-872d-dd0724c80f7a.png"><img width="300" alt="965d242 HighPerformance" src="https://user-images.githubusercontent.com/456942/64073912-367f9f80-cc59-11e9-872d-dd0724c80f7a.png"></a>|

**Comment by kvark** [comment] 2019-09-03 01:38
@parasyte thank you for the data! I'm quite puzzled here. Looking at a GPU capture on Intel, I see that rendering into layers of the shadow is totally correct, but the texture looks wrong when it's being sampled from.

End of rendering (to layer 0):
![shadow-depth0](https://user-images.githubusercontent.com/107301/64138137-b62c7c00-cdc9-11e9-8bb2-67539679bdcb.png)
Sampling from layer 0:
<img width="428" alt="Screen Shot 2019-09-02 at 21 35 34" src="https://user-images.githubusercontent.com/107301/64138147-bc225d00-cdc9-11e9-9ad0-2dbd41770364.png">

My guess is that Apple runtime and/or driver doesn't insert proper transition barriers for the case of rendering being done to layers of a 2D array depth texture. I'd expect this to be a responsibility of the driver, in which case having it wrong in multiple IHVs is strange. Perhaps, it's Metal runtime that fails?

@litherum fyi, this was filed on the radar as 48911699 (also got assigned FB5398663) for NVidia, but it appears to affect other vendors as well. Please let us know if there is anything we can provide. Reproducing today is easy:
```
git clone https://github.com/gfx-rs/wgpu-rs
cargo run --example shadow
```

**Comment by tomgreen66** [comment] 2021-08-25 14:09
Whats the latest with this issue?  On latest of Big Sur and using Intel Iris Pro graphics and it seems to have a similar rendering bug.  Were any fixes applied by Apple?

```
     Running unittests (target/debug/examples/shadow-2a69e77289900e7b)

running 1 test
test shadow ... FAILED

failures:

---- shadow stdout ----
thread 'shadow' panicked at 'Image data mismatch! Outlier count 1271063 over limit 500. Max difference 192', wgpu/examples/shadow/../../tests/common/image.rs:134:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'shadow' panicked at 'UNEXPECTED TEST FAILURE', wgpu/examples/shadow/../../tests/common/mod.rs:301:9


failures:
    shadow

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5.84s
```

![image](https://user-images.githubusercontent.com/2301394/130806008-2394a9b8-9f3b-49f1-b9b9-9a574c314b3f.png)

**Comment by kvark** [comment] 2021-08-25 14:29
@tomgreen66 I filed this issue years ago, and it got resolved by Apple. But apparently their fix only starts kicking in on a second frame, while the testing infrastructure has the first frame, which shows the same issue... So it's still a bug on Apple, but we need to report it again. And technically it's harmlesss.

**Comment by cwfitzgerald** [comment] 2024-12-11 20:21
I'm going to close this, pending reproduction on up to date wgou/metal.

**Closed** 2024-12-11 20:21 UTC
Labels: external: driver-bug, api: metal

**Comment by teoxoy** [comment] 2024-12-12 15:27
People seem to easily reproduce in https://github.com/bevyengine/bevy/issues/3315. I asked if someone there could put up a wgpu repro.
