### ISSUE TITLE
Artifacting with non-uniform indexing of texture arrays

### ISSUE THREAD

**Issue by tim-harding** [gfx-rs/wgpu#4029] opened 2023-08-11 03:20 UTC
**Description**
When trying to use the `SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING` feature, there is strange glitching in the sampled textures. 

**Repro steps**
Run the provided `texture-arrays` example and resize the window for various artifact patterns. 

**Expected vs observed behavior**
Textures should render the same as with uniform indexing. Instead, they do not. 

**Extra materials**
Here is the trace output from running the `texture-arrays` example:
[trace.zip](https://github.com/gfx-rs/wgpu/files/12318381/trace.zip)
Here are several screenshots from the included `texture-arrays` sample binary with different window sizes:
![1691722377_grim](https://github.com/gfx-rs/wgpu/assets/13814470/e2de5ed1-8af8-49dc-b08f-681afd102bff)
![1691722411_grim](https://github.com/gfx-rs/wgpu/assets/13814470/918ad038-b4fb-48ce-b66d-eff73dea41d1)
And a more severe example in which I am trying to render a font with each glyph on a separate texture:
![1691721687_grim](https://github.com/gfx-rs/wgpu/assets/13814470/97121e08-c165-4cf2-b6e3-252793d8810f)
Running the `texture-arrays` example with `WGPU_TEXTURE_ARRAY_STYLE=uniform` gives normal output. I am using Wayland but setting `WINIT_UNIX_BACKEND=x11` makes no difference. 

**Platform**
The example images shown use version 0.17 from the `trunk` branch. I am running on `6.4.9-arch1-1` with the Sway window manager. Below is information about my adapter as provided by the `wgpu-info` binary:
```text
   Backend: Vulkan
      Name: "AMD Radeon RX 6600 (RADV NAVI23)"
  VendorID: 4098
  DeviceID: 29695
      Type: DiscreteGpu
    Driver: "radv"
DriverInfo: "Mesa 23.1.5"
 Compliant: true
```

**Comment by cwfitzgerald** [comment] 2023-08-11 03:46
Thanks for the detailed report!

This is a dupe of https://github.com/gfx-rs/naga/issues/2408, and should be fixed in the next point release of Naga!

**Comment by tim-harding** [comment] 2023-08-11 04:33
Delightful! Thanks heaps. I'll add a patch to my dependencies until the dependency is bumped in `wgpu` 😊

**Closed as not planned** 2023-08-11 20:43 UTC
