### ISSUE TITLE
DX12 Assertion failed left: -2005270523 with read only buffer

### ISSUE THREAD

**Issue by MrMarnic** [gfx-rs/wgpu#1481] opened 2021-06-06 20:07 UTC
**Description:**
I have a storage buffer that contains all the matrix data. Every object in my game has an offset for it's data in this buffer.

My shader looks like this:
`layout(set=2, binding=0).
readonly buffer StorageBuffer{
    mat4 transform;.
};`
(This is only a small snippet for the relevant part.)

I am creating the buffer like this:
`let buffer = device.create_buffer(&BufferDescriptor {
            label: None,
            size: BIND_BUFFER_ALIGNMENT * 100,
            usage: BufferUsage::STORAGE | BufferUsage::COPY_DST,
            mapped_at_creation: false
        });`

Here is the code bindgroup:
`device.create_bind_group_layout(&BindGroupLayoutDescriptor { label: None, entries: &[BindGroupLayoutEntry {
            binding: 0,
            visibility: ShaderStage::VERTEX,
            ty: BindingType::Buffer { ty: BufferBindingType::Storage {
                read_only: true
            },has_dynamic_offset: true, min_binding_size: BufferSize::new(64) },
            count: None
        }] })`

In the render pass I am using it like this:
`render_pass.set_bind_group(2,&camera.transform_bind_group,&[offset]);`

If I change the storage buffer to a uniform buffer (in the shader too) everything is working.

The thing is this is all working perfectly fine on the VULKAN backend (with the storage buffer).
I only wanted to test DX12 out and then I noticed this bug.

**Extra materials:**
panic:
`thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `-2005270523`,
 right: `0`: error on command list creation: 887a0005'`

**Repro steps**
Use the DX12 backend.
Use a SSBO in a shader.

**Expected vs observed behavior**
panic vs no panic
No panic on DX12 and VULKAN vs panic on DX12

**Backtrace:**
pastebin: https://pastebin.com/2kRXLB1Z

**Platform**
OS: Windows 10
GPU: NVIDIA GeForce GTX 1080 Ti
Device-Type: DiscreteGpu
wgpu-version: 0.8.1

**Comment by cwfitzgerald** [comment] 2021-06-09 05:00
So this is a loss of device. If you can run it through visual studio and it will give you more information about why the device was lost. We should be able to get this data once #1383 is fixed.

**Comment by MrMarnic** [comment] 2021-06-27 16:28
How can I run it through visual studio?

**Comment by cwfitzgerald** [comment] 2021-06-27 21:09
Go to visual studio, click "open project or solution" and open the exe directly, this will let you run the program with the debug layers on.

**Comment by MrMarnic** [comment] 2021-06-28 05:25
Here is the log:
https://gist.github.com/MrMarnic/1e40570bba35c805f0fbd576c74caa52

**Comment by cwfitzgerald** [comment] 2021-06-28 05:43
Funky stuff, there's nothing in the log saying why the device was removed, unless I missed it in the array of weird com(?) issues

**Comment by cwfitzgerald** [comment] 2021-06-28 05:44
Oh, was this running in debug or release?

**Comment by MrMarnic** [comment] 2021-06-28 14:41
It was running in release. Here is the debug log:
https://gist.github.com/MrMarnic/2d1197dded6a7e021c15802c2c5bd7e0

**Comment by kvark** [comment] 2021-06-28 14:45
Thank you!
Root signature is inconsistent:
> D3D12 ERROR: ID3D12CommandList::SetGraphicsRootConstantBufferView: The currently set root signature declares parameter [2] with type SRV, so it is invalid to set a root CBV here. [ EXECUTION ERROR #710: SET_ROOT_CONSTANT_BUFFER_VIEW_INVALID]
D3D12 ERROR: ID3D12CommandList::SetGraphicsRootConstantBufferView: The currently set root signature declares parameter [3] with type SRV, so it is invalid to set a root CBV here. [ EXECUTION ERROR #710: SET_ROOT_CONSTANT_BUFFER_VIEW_INVALID]
D3D12 ERROR: ID3D12CommandList::ClearUnorderedAccessViewUint: The CPU and GPU descriptor handles refer to unmatched descriptors. ClearUnorderedAccessView* methods require that the GPU and CPU descriptor handles reside in separate shader-visible and non-shader-visible descriptor heaps resptively. These descriptors must otherwise be identical. [ EXECUTION ERROR #646: INVALID_DESCRIPTOR_HANDLE]

**Comment by kvark** [comment] 2021-06-28 14:49
Please record an API trace and attach here (zipped). See https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications#tracing-infrastructure

**Comment by MrMarnic** [comment] 2021-06-28 16:47
Here is the trace.
[trace.zip](https://github.com/gfx-rs/wgpu/files/6727975/trace.zip)

**Comment by kvark** [comment] 2021-07-01 02:37
Thank you for the trace! I haven't looked at it yet, but I think what could happen is:
  - you write shaders in GLSL and provide in SPIR-V
  - naga failed to parse SPIR-V, so validation got turned off
  - the pipeline layout is not compatible with the pipeline

If you have Rust logging hooked up, you should see a relevant warning.

**Comment by kvark** [comment] 2021-07-01 02:47
Just checked, looks like the SPIR-V is parsed correctly. Will try to replay on Windows.

**Comment by kvark** [comment] 2021-07-01 05:02
It turns out, our support for dynamic offsets didn't extend to storage buffers adequately... Fixed in https://github.com/gfx-rs/gfx/commit/dc0fdb259b50f74291d9917be8ecd9bf1a44286f, which can be picked up by `cargo update -p gfx-backend-dx12`

**Closed by kvark** 2021-07-01 05:02 UTC
Labels: help wanted, type: bug

**Comment by MrMarnic** [comment] 2021-07-01 16:44
Thank you very much, but I have a new problem now:
https://gist.github.com/MrMarnic/dc0e572fb7857a6e10dbcbf12d83a2e7

**Comment by kvark** [comment] 2021-07-02 01:04
What exactly is the problem now? The new log doesn't show any D3D errors firing up.

**Comment by MrMarnic** [comment] 2021-07-02 14:14
I get this error now:

https://gist.github.com/MrMarnic/5a302395a71ef1f553553adbc46debd8

**Comment by kvark** [comment] 2021-07-02 14:17
We definitely want to fix that one as well! Could you please file an issue and provide a way to reproduce. There is a chance API trace isn't going to help us with this, since the problem occurs in staging buffer allocation.

**Comment by kvark** [comment] 2021-07-02 14:17
A log from Visual Studio would be most helpful

**Comment by MrMarnic** [comment] 2021-07-05 20:09
It is working with wgpu-version 0.9.0. The older version was the problem.

**Comment by kvark** [comment] 2021-07-05 20:32
Are you fine using wgpu-0.9 from here on? It would be nice to not spend time on patching 0.8 at this point.

**Comment by MrMarnic** [comment] 2021-07-05 20:58
Yes I will
