### ISSUE TITLE
Panic due to out of bounds slice access when using push constants in render bundle

### ISSUE THREAD

**Issue by john01dav** [gfx-rs/wgpu#2749] opened 2022-06-08 04:14 UTC
**Description**
I am trying to use `RenderBundle`s in my wgpu program, which uses push constants in the bundled commands. I am encountering an out of bounds panic [here](https://github.com/gfx-rs/wgpu/blob/3f4144a53b5ce80b9d89655f84534cfee74fc1ba/wgpu-core/src/command/bundle.rs#L705). Even if I am misusing push constants somehow (which I suspect is unlikely as basically the same thing without a `RenderBundle` works as expected), there should be a user-friendly error message that explains my error (even if in panic form) instead of a cryptic panic. 

**Repro steps**
I'll make an MCVE soonish, but I wanted to get the bug report out. As far as I can tell, just push constants + RenderBundle is all that's needed. In the mean time, I can privately share my actual code base that's having the error with a wgpu developer. 

**Expected vs observed behavior**
I expect the panic to either not happen or provide a user-friendly error message.

**Extra materials**
None seem needed. Let me know if you need something.

**Platform**
Although this version of Fedora uses Wayland by default, I am on X because Wayland was causing issues. I am using wgpu 0.12.0 from crates.io with the spirv feature enabled. 
```
$ neofetch
             .',;::::;,'.                david@fedora 
         .';:cccccccccccc:;,.            ------------ 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 36 (Workstation Editi 
    .:cccccccccccccccccccccccccc:.       Host: Z390 M GAMING 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 5.17.12-300.fc36.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 22 mins 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 2730 (rpm) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: fish 3.4.1 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 1440x900, 1920x1080, 1920x 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: GNOME 42.2 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: Mutter 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: Adwaita 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: Materia-dark-compact [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: Adwaita [GTK2/3] 
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: gnome-terminal 
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: Intel i9-9900K (16) @ 5.000GHz 
:cccccccccccccccccccccccccccc:'.         GPU: Intel CoffeeLake-S GT2 [UHD Graph 
.:cccccccccccccccccccccc:;,..            GPU: NVIDIA GeForce GTX 1070 
  '::cccccccccccccc::;,.                 Memory: 5622MiB / 31958MiB 
```

**Comment by cwfitzgerald** [comment] 2022-06-08 04:19
Thanks for filling! This is a duplicate of #2683, but thank you for the additional info!

**Closed by cwfitzgerald** 2022-06-08 04:19 UTC

**Comment by john01dav** [comment] 2022-06-08 04:30
Sorry for the double report. I searched the issues for the panic message and found none, so I thought that it wasn't reported yet.

**Comment by cwfitzgerald** [comment] 2022-06-08 05:00
All good! Would much rather have multiple reports than no reports at all!
