### ISSUE TITLE
Re-mapping buffer does not work

### ISSUE THREAD

**Issue by lucacasonato** [gfx-rs/wgpu#1269] opened 2021-03-16 18:38 UTC
**Description**

When creating a buffer, writing to it, unmapping it, mapping it again, then reading, the read buffer does not match the written buffer.

**Repro steps**

Comes from cts test `webgpu:api,operation,buffers,map:mapAsync,read:size=12;range=[]`

```ts
    const range = [];
    const size = 12;
    const rangeSize = 12;

    const buffer = device.createBuffer({
      mappedAtCreation: true,
      size,
      usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.MAP_READ,
    });
    const init = buffer.getMappedRange(...range);

    assert(init.byteLength === rangeSize);
    const expected = new Uint32Array(new ArrayBuffer(rangeSize));
    const data = new Uint32Array(init);
    for (let i = 0; i < data.length; ++i) {
      data[i] = expected[i] = i + 1;
    }
    buffer.unmap();

    await buffer.mapAsync(GPUMapMode.READ);
    const actual = new Uint8Array(buffer.getMappedRange(...range));
```

**Expected vs observed behavior**

Written buffer is `0x010000000200000003000000`, read buffer is `0x000000000000000000000000`.

**Extra materials**

[trace.zip](https://github.com/gfx-rs/wgpu/files/6151450/trace.zip)

**Platform**

wgpu: 5d993efc8519dbcaffb04a5f577e11263c1023e8
Linux: Ubuntu 20.04
GTX 1070 - Vulkan

**Comment by teoxoy** [comment] 2024-08-07 14:22
Closing as duplicate of https://github.com/gfx-rs/wgpu/issues/5173.

**Closed by teoxoy** 2024-08-07 14:22 UTC
Labels: type: bug, help required
