### ISSUE TITLE
Buffer data shows up as zeroes under wgpu 0.9.0

### ISSUE THREAD

**Issue by blakej11** [gfx-rs/wgpu#1582] opened 2021-07-01 23:34 UTC
**Description**
I have a small program (a Game of Life implementation) that I had working under wgpu 0.8.0. When I changed `Cargo.toml` to use wgpu 0.9.0 instead, it stopped working.

At its core, there are a pair of buffers that are used for the Life algorithm. The Rust-based control code alternates between using #0 as the source and #1 as the destination, and vice-versa, on alternate invocations of the algorithm. Buffer #0 is initialized using random data at the start of the program.

Under 0.9.0, I observed that if I added a `copy_buffer_to_buffer` call immediately after enqueueing the invocation of the compute kernel, I would be able to see the results of the computation. But if I called `queue.submit(Some(command_encoder.finish()))` to invoke the compute kernel, and then made another `CommandEncoder` to copy the results, the results would show up as all zeroes. This was confirming the graphical behavior that I saw in 0.9.0 - the very first frame (with the random data) would be rendered as expected, but all subsequent frames would show up as black.

**Repro steps**
I've attached four trace logs:

- one from "0.9.0 fails", where the `copy_buffer_to_buffer` was in its own `CommandEncoder` and indeed returned all zeroes (for the first four cells that I looked at).
- one from "0.9.0 works", where `copy_buffer_to_buffer` was in the same `CommandEncoder` as the compute kernel, and it showed non-zero values. (The fundamental problem was still present, though - all frames after the first one rendered as black.)
- one from "0.8.0 fails" and "0.8.0 works", which despite the names both actually had the correct visible behavior. They only differ by where the `copy_buffer_to_buffer` call was, exactly analogously to the versions from 0.9.0.

If source code would be helpful I can provide that as well.

**Expected vs observed behavior**
See above.

**Extra materials**
[trace.0.8.fails.zip](https://github.com/gfx-rs/wgpu/files/6751253/trace.0.8.fails.zip)
[trace.0.8.works.zip](https://github.com/gfx-rs/wgpu/files/6751254/trace.0.8.works.zip)
[trace.0.9.fails.zip](https://github.com/gfx-rs/wgpu/files/6751256/trace.0.9.fails.zip)
[trace.0.9.works.zip](https://github.com/gfx-rs/wgpu/files/6751257/trace.0.9.works.zip)

**Platform**
MacOS 11.4, wgpu 0.8.0/0.9.0 as described above.

**Comment by blakej11** [comment] 2021-07-02 00:07
Here's the source code: [life-0.1.0.zip](https://github.com/gfx-rs/wgpu/files/6751341/life-0.1.0.zip)

**Comment by AnotherNathan** [comment] 2021-07-02 19:47
I'm pretty sure this is a duplicate of #1555.
It should already be fixed on master.
As a workaround, you can manually call CommandEncoder::clear_buffer before you use the cell buffers for the first time, then it works fine.

**Comment by Wumpf** [comment] 2021-07-02 20:24
confirmed, this got fixed in #1561

**Closed** 2021-07-02 21:30 UTC
Labels: help wanted, type: bug
