### ISSUE TITLE
panic during translation .frag -> .spv (validation successful): entered unreachable code

### ISSUE THREAD

**Issue by Vipitis** [gfx-rs/wgpu#4549] opened 2023-10-24 00:03 UTC
Hey,

I have encountered shader programs that validate but panic during translation to spir-v. While looking for a minimal example, I constructed this [shadertoy](https://www.shadertoy.com/view/dsGBWR) and it's [wsgl.frag varaint](https://gist.github.com/Vipitis/45e3181d1d6c81641c2b0411e56080fa) (via wgpu-py)

So there might be an issue where validation for glsl doesn't correctly catch some issue in the code (although it's valid originally) and therefore crashes during translation. Full backtrace as follows:
```bash
thread 'main' panicked at C:\Users\Jan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\naga-0.13.0\src\back\spv\block.rs:2066:56:
internal error: entered unreachable code: Expression [15] is not cached!
stack backtrace:
   0:     0x7ff7944e2d8a - <unknown>
   1:     0x7ff7944fb47b - <unknown>
   2:     0x7ff7944dfcb1 - <unknown>
   3:     0x7ff7944e2b0a - <unknown>
   4:     0x7ff7944e510a - <unknown>
   5:     0x7ff7944e4d78 - <unknown>
   6:     0x7ff7944e57be - <unknown>
   7:     0x7ff7944e56ad - <unknown>
   8:     0x7ff7944e3779 - <unknown>
   9:     0x7ff7944e53b0 - <unknown>
  10:     0x7ff79451d905 - <unknown>
  11:     0x7ff794400d8d - <unknown>
  12:     0x7ff7944130f1 - <unknown>
  13:     0x7ff79441caef - <unknown>
  14:     0x7ff794421942 - <unknown>
  15:     0x7ff794423384 - <unknown>
  16:     0x7ff79424fa10 - <unknown>
  17:     0x7ff79424d347 - <unknown>
  18:     0x7ff79425ec56 - <unknown>
  19:     0x7ff794266fdc - <unknown>
  20:     0x7ff7944d9d18 - <unknown>
  21:     0x7ff794253bfc - <unknown>
  22:     0x7ff794503438 - <unknown>
  23:     0x7ffcc9db7344 - BaseThreadInitThunk
  24:     0x7ffccb8626b1 - RtlUserThreadStart
```

potential duplicate of https://github.com/gfx-rs/wgpu/issues/4540, https://github.com/gfx-rs/wgpu/issues/4517, https://github.com/gfx-rs/wgpu/issues/4464

**Comment by Vipitis** [comment] 2023-10-27 01:01
I installed `naga-cli` from cargo to get 0.14.0. Issue still persists.

```bash
thread 'main' panicked at C:\Users\Jan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\naga-0.14.0\src\back\spv\block.rs:2098:56:
internal error: entered unreachable code: Expression [15] is not cached!
```

seems to still reference the same line of code.

**Comment by fornwall** [comment] 2023-11-18 18:51
Reduced test case (converting this wgsl to spv panics as described above):

```wgsl
fn func(a: ptr<function, f32>) {}

@fragment 
fn main() {
    var v = vec2(0.0);
    func(&v.x);
}
```

**Comment by jimblandy** [comment] 2024-02-06 14:55
Looks like a duplicate of #4517.

**Closed as not planned by jimblandy** 2024-02-06 14:55 UTC
Labels: type: bug, area: naga back-end, naga, lang: SPIR-V
