### ISSUE TITLE
Cannot allocate buffers over 4GiB due to limit type definitions

### ISSUE THREAD

**Issue by iamseb** [gfx-rs/wgpu#2337] opened 2021-12-30 16:47 UTC
**Description**
WGPU defines limits for buffer allocation (along with other device memory limits) in wgpu::Limits. Device memory limits are all defined as u32, making it impossible to allocate a single buffer beyond 4GiB where this is suported by the device and backend.

For example, wgpu::Limits::max_storage_buffer_binding_size is defined as a u32, setting a limit of 4GiB for the size of buffers. However, Vulkan allows allocation of buffers up to available device memory. All memory allocation sizes in Vulkan use the VKDeviceSize type, which is defined as a uint64_t.

**Repro steps**
```
let mut gpu_limits = wgpu::Limits::default();
gpu_limits.max_storage_buffer_binding_size = 2u64 << 34; // try to set the storage buffer limit to 16GiB
```

**Expected vs observed behavior**
Observed:
```
error[E0308]: mismatched types: expected u32, found u64
```

Expected: successful compilation.

**Platform**
Windows 10, Vulkan backend. Will also be an issue for any backend that allows allocation of device memory above 32 bit limits.

**Comment by kvark** [comment] 2021-12-30 16:48
Thank you for filing! We need to change the relevant limits (only) to u64.

**Comment by aevyrie** [comment] 2023-05-12 22:42
Looked into this briefly as one of my coworkers ran into this (@bonsairobo).

It appears that he was being capped at 2GB, which seems to be caused by the fact that when determining limits, the wgpu setting is `min`ed with an `132`: `MAX_I32_BINDING_SIZE`:

https://github.com/gfx-rs/wgpu/blob/372ac9b529613792e82ce265ce946e453779d0e8/wgpu-hal/src/vulkan/adapter.rs#L754-L759

This suggests to me that this goes beyond a simple public API type change, into some fundamental design constraints of the underlying backends. Looking into this const, yields: 

https://github.com/gfx-rs/wgpu/blob/372ac9b529613792e82ce265ce946e453779d0e8/wgpu-hal/src/auxil/mod.rs#L43-L47

Here's a quick overview of where the type gets used. Notable (to me) was how certain backends are already casting this to u32, or in the case of Metal, doing something funky with an intermediate u64 cast:

https://github.com/search?q=repo%3Agfx-rs%2Fwgpu%20max_storage_buffer_binding_size&type=code

I don't know much about graphics backends, but hopefully this is useful to anyone attempting to tackle the issue.

**Comment by cwfitzgerald** [comment] 2023-05-16 15:52
We've hit overflows in drivers on buffers above 1gb - the max buffer size is currently capped at 1GB for this reason.

I honestly don't see buffers over 1gb being supported any time soon. Getting an allocation for a 1GB+ buffer is already hard enough as even the slightest fragmentation can cause problems. Going above 1GB you should be allocating multiple buffers and either using a binding array or chunking your operations.

I'm going to close this as I don't think there's anything to do about it, but the issue log will help people trying to deal with this in the future.

**Closed by cwfitzgerald** 2023-05-16 15:52 UTC
Labels: help wanted, area: api

**Comment by bonsairobo** [comment] 2023-05-17 07:11
@cwfitzgerald I'm not familiar with "binding array"s, can you link to some documentation?

For more context, we want to be able to allocate a large pool of fixed-size pages on the GPU.

**Comment by Wumpf** [comment] 2023-05-17 07:27
@bonsairobo  Binding arrays are a native-only feature that allows binding arrays of buffers/textures instead of having a binding for every single resource. The feature docs here talk about it a bit https://github.com/gfx-rs/wgpu/blob/trunk/wgpu-types/src/lib.rs#L501
