### ISSUE TITLE
get_current_texture memory leak on OSX

### ISSUE THREAD

**Issue by FredrikNoren** [gfx-rs/wgpu#2126] opened 2021-10-29 09:34 UTC
**Description**
get_current_texture seems to be leaking memory on OSX when the application is not visible on the screen.

**Repro steps**
Start a wgpu application, move it behind something or to another desktop so that it's not visible, check memory usage.

**Extra materials**
I'm using this method to run it with tokio: https://gist.github.com/FredrikNoren/7c3535b11e99e8fcd8dd3d55f9a934a2
I used cargo-instruments to profile the application.
<img width="1552" alt="Screenshot 2021-10-29 at 11 14 04" src="https://user-images.githubusercontent.com/1288009/139412147-dbe6251b-06d9-43f0-aa73-b907338482b5.png">

**Platform**
OSX, M1 Air 2020, Big Sur, wgpu 0.11.0

**Comment by cwfitzgerald** [comment] 2021-10-29 18:15
Duplicate of #1783.

**Closed by cwfitzgerald** 2021-10-29 18:15 UTC
