### ISSUE TITLE
Program not running and just crashing.

### ISSUE THREAD

**Issue by jyash8** [gfx-rs/wgpu#6355] opened 2024-10-02 06:17 UTC
**Description**
I was trying, hello_triangle. Program compiled. But it crashed when running

**Repro steps**
just compiled and ran your hello_triangle example

**Expected vs observed behavior**
Program should run and a window should be shown.

**Extra materials**
Here are the logs:
```
wp_linux_drm_syncobj_manager_v1#47: error 0: Surface already has a syncobj attached
[2024-10-02T06:04:48Z ERROR wgpu_hal::vulkan::adapter] get_physical_device_surface_present_modes: ERROR_SURFACE_LOST_KHR
[2024-10-02T06:04:48Z ERROR wgpu_hal::vulkan::adapter] get_physical_device_surface_formats: ERROR_SURFACE_LOST_KHR
thread 'main' panicked at wgpu/src/backend/wgpu_core.rs:722:18:
Error in Surface::configure: Validation Error

Caused by:
  Requested present mode Mailbox is not in the list of supported present modes: []

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here is the complete backtrace:
```
xkbcommon: ERROR: couldn't find a Compose file for locale "en_IN" (mapped to "en_IN.ISO8859-1")
wp_linux_drm_syncobj_manager_v1#47: error 0: Surface already has a syncobj attached
[2024-10-02T06:12:03Z ERROR wgpu_hal::vulkan::adapter] get_physical_device_surface_present_modes: ERROR_SURFACE_LOST_KHR
[2024-10-02T06:12:03Z ERROR wgpu_hal::vulkan::adapter] get_physical_device_surface_formats: ERROR_SURFACE_LOST_KHR
thread 'main' panicked at wgpu/src/backend/wgpu_core.rs:722:18:
Error in Surface::configure: Validation Error

Caused by:
  Requested present mode Mailbox is not in the list of supported present modes: []

stack backtrace:
   0:     0x55a1e70cc916 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55a1e70cc916 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a1e70cc916 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55a1e70cc916 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55a1e70f73c0 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x55a1e70f73c0 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x55a1e70c9f2f - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x55a1e70cc6f4 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55a1e70cc6f4 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55a1e70cdc57 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x55a1e70cd9b9 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x55a1e70ce0e8 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x55a1e70cdfc2 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x55a1e70cce16 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55a1e70cdd20 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x55a1e5a18135 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x55a1e65f2537 - wgpu::backend::wgpu_core::ContextWgpuCore::handle_error_fatal::h5ff1d5f1db0e9c84
                               at /home/jyash8/wgpu/wgpu/src/backend/wgpu_core.rs:332:9
  17:     0x55a1e6610c7e - <wgpu::backend::wgpu_core::ContextWgpuCore as wgpu::context::Context>::surface_configure::hbac8ab8078bde81d
                               at /home/jyash8/wgpu/wgpu/src/backend/wgpu_core.rs:722:13
  18:     0x55a1e65f480b - <T as wgpu::context::DynContext>::surface_configure::h97f2f8ad3a16d058
                               at /home/jyash8/wgpu/wgpu/src/context.rs:1459:9
  19:     0x55a1e65cf7b5 - wgpu::api::surface::Surface::configure::h80baac00bf5621f1
                               at /home/jyash8/wgpu/wgpu/src/api/surface.rs:89:9
  20:     0x55a1e5d61803 - wgpu_examples::hello_triangle::run::{{closure}}::{{closure}}::h688f0ebcd1f79795
                               at /home/jyash8/wgpu/examples/src/hello_triangle/mod.rs:102:25
  21:     0x55a1e5d60060 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h838744fc97465970
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:294:13
  22:     0x55a1e5dcc166 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::single_iteration::h8cf71b8909667602
                               at /home/jyash8/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/wayland/event_loop/mod.rs:425:17
  23:     0x55a1e5daf7ea - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::pump_events::h54b87e797809a65e
                               at /home/jyash8/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/wayland/event_loop/mod.rs:230:13
  24:     0x55a1e5db3349 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_on_demand::hea05d7d7feef6aca
                               at /home/jyash8/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/wayland/event_loop/mod.rs:200:19
  25:     0x55a1e5cd9165 - winit::platform_impl::platform::EventLoop<T>::run_on_demand::he4157d664280438c
                               at /home/jyash8/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/mod.rs:829:56
  26:     0x55a1e5cd9e8a - winit::platform_impl::platform::EventLoop<T>::run::hae6f3217c430d35d
                               at /home/jyash8/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/mod.rs:822:9
  27:     0x55a1e5cdadfa - winit::event_loop::EventLoop<T>::run::h6a5376a2673ce51c
                               at /home/jyash8/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/event_loop.rs:249:9
  28:     0x55a1e5d613bd - wgpu_examples::hello_triangle::run::{{closure}}::hfe4c173174bbfd95
                               at /home/jyash8/wgpu/examples/src/hello_triangle/mod.rs:85:5
  29:     0x55a1e5a1b001 - pollster::block_on::h59c59e85c6e80f11
                               at /home/jyash8/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pollster-0.3.0/src/lib.rs:128:15
  30:     0x55a1e5c11207 - wgpu_examples::hello_triangle::main::h7fb4e85a7a312ae2
                               at /home/jyash8/wgpu/examples/src/hello_triangle/mod.rs:171:9
  31:     0x55a1e5a1984f - wgpu_examples::main::ha3808ee01bca89b4
                               at /home/jyash8/wgpu/examples/src/main.rs:229:5
  32:     0x55a1e5a18bcb - core::ops::function::FnOnce::call_once::hdfad0f00b96a6596
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  33:     0x55a1e5a18d8e - std::sys_common::backtrace::__rust_begin_short_backtrace::h286101c74847aa76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
  34:     0x55a1e5a191e1 - std::rt::lang_start::{{closure}}::hbecdb6cf139ecafc
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
  35:     0x55a1e70c26c1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  36:     0x55a1e70c26c1 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  37:     0x55a1e70c26c1 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  38:     0x55a1e70c26c1 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  39:     0x55a1e70c26c1 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  40:     0x55a1e70c26c1 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  41:     0x55a1e70c26c1 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  42:     0x55a1e70c26c1 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  43:     0x55a1e70c26c1 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  44:     0x55a1e5a191ba - std::rt::lang_start::h99eae8e79bc1d76c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:165:17
  45:     0x55a1e5a1992e - main
  46:     0x7ef4b48a7e08 - <unknown>
  47:     0x7ef4b48a7ecc - __libc_start_main
  48:     0x55a1e5a18a75 - _start
  49:                0x0 - <unknown>
```

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.
OS: EndeavourOS (Arch-based)
Kernel: Linux 6.11.1-arch1-1
Using hyprland as window manager problem but also in KDE(wayland)
GPU: Intel Integrated / Nvidia Geforce 3050 mobile
GPU driver: i1915 / nvidia (proprietary) 560.35.03
wgpu : v22.1.0

**Comment by Wumpf** [comment] 2024-10-02 17:08
Looks like a duplicate of
* #6320

please let me know if there's reason to believe otherwise, thank you!

**Closed as not planned by Wumpf** 2024-10-02 17:08 UTC
Labels: platform: wayland

**Comment by jyash8** [comment] 2024-10-03 01:59
When will this get fixed ?

**Comment by Wumpf** [comment] 2024-10-03 06:51
@jyash8 within the core maintainer group there's afaik right now nobody using Wayland actively. This family of issue seems to be very config/machine dependent, making it really hard to repro. Furthermore, from those everyone at Mozilla has to prioritize everything towards WebGPU compliance right now and everything surfaces/presentation isn't part of that.
Therefore, this area is particularly reliant on contributions which would be very welcome!
-> it will be fixed once someone shows up and fixes it ;-)
