### ISSUE TITLE
ERROR gfx_backend_vulkan VALIDATION [VUID-vkDestroyDevice-device-00378 (0x71500fba)]

### ISSUE THREAD

**Issue by o-micron** [gfx-rs/wgpu#1478] opened 2021-06-05 06:57 UTC
I ran into a bug while running hello-compute example.
`cargo run --example hello-compute`
I used the master branch ... last commit `7978df83ef2be0835a621804958582358f398a95`

Backend: Vulkan
Platform: Windows 10

```
No numbers were provided, defaulting to [1, 2, 3, 4]
[2021-06-05T06:43:06Z ERROR gfx_backend_vulkan]
    VALIDATION [VUID-vkDestroyDevice-device-00378 (0x71500fba)] : Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x20a24eab1a0, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0xf4f1d50000000009, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x20a24eab1a0[], VkDeviceMemory 0xf4f1d50000000009[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
    object info: (type: DEVICE, hndl: 0x20a24eab1a0), (type: DEVICE_MEMORY, hndl: 0xf4f1d50000000009)

Steps: [0, 1, 7, 2]
```

I guess that's a typical vulkan error message pointing out that you destroyed the device before destroying the device memory prior to that ? I see the example only created a staging buffer and a storage buffer ...

Link [https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378](https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)

**Comment by cwfitzgerald** [comment] 2021-06-09 05:59
Thanks for filing! This is very likely a duplicate of #1400. Once this is fixed, if this is still a problem after that it is, please re-open.

**Closed by cwfitzgerald** 2021-06-09 05:59 UTC
Labels: help wanted, type: bug
