### ISSUE TITLE
OpenGL 4.1 on macOS doesn't support GL_EXT_texture_shadow_lod

### ISSUE THREAD

**Issue by bes** [gfx-rs/wgpu#5364] opened 2024-03-07 20:42 UTC
**Description**
When using Bevy on macOS with an OpenGL 4.1 core context, it's not possible to compile some shaders because the application crashes with the following error:

```shell
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    Internal error in ShaderStages(FRAGMENT) shader: ERROR: 0:2: '' :  extension 'GL_EXT_texture_shadow_lod' is not supported
```

Probably introduced by https://github.com/gfx-rs/wgpu/pull/5171

**Repro steps**
Unfortunately a little bit complicated, I use an OpenGL 4.1 core context that I received from GStreamer.

**Expected vs observed behavior**
I would like to be able to disable the `GL_EXT_texture_shadow_lod` extension using a feature.

**Platform**
* macOS
* OpenGL 4.1 Core
* Using wgpu `trunk` at commit `14dbf8c60e9e20fdd8d27c28e907d3e1208690dc`

**Comment by bes** [comment] 2024-03-07 20:54
Maybe related to https://github.com/gfx-rs/wgpu/issues/5344 ?

**Comment by teoxoy** [comment] 2024-03-11 10:41
Closing as duplicate of https://github.com/gfx-rs/wgpu/issues/5344.

**Closed as not planned by teoxoy** 2024-03-11 10:41 UTC
