### ISSUE TITLE
BindGroupLayout[Id(0,1,mtl)] does not exist (recreating the same wgpu::Device)

### ISSUE THREAD

**Issue by CGessinger** [gfx-rs/wgpu#6133] opened 2024-08-19 17:21 UTC
**Description**
BindGroupLayouts behave weirdly when recreating the same wgpu::Device. When a request a device and use it to create a BindGroupLayout but then request the same deivce again and try to use the BindGroupLayout wgpu panics with: `BindGroupLayout[Id(0,1,mtl)] does not exist`. However, when I create a new BindGroupLayout on the device2 without doing anything with it, then I can use the BindGroupLayout I created with device1.

**Repro steps**
```rust
use pollster::FutureExt;

fn create_device() -> wgpu::Device {
    let instance = wgpu::Instance::default();
    let adapter = instance
        .request_adapter(&wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::default(),
            force_fallback_adapter: false,
            compatible_surface: None,
        })
        .block_on()
        .expect("Failed to find an appropriate adapter");

    let (device, _) = adapter
        .request_device(
            &wgpu::DeviceDescriptor {
                label: None,
                required_features: wgpu::Features::empty(),
                required_limits: wgpu::Limits::downlevel_defaults(),
                memory_hints: wgpu::MemoryHints::MemoryUsage,
            },
            None,
        )
        .block_on()
        .expect("Failed to create device");

    device
}

fn main() {
    let device = create_device();

    let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
        label: None,
        entries: &[],
    });

    let device = create_device();

    // Uncommenting this makes it work!
    // let dummy_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
    //     label: None,
    //     entries: &[],
    // });

    let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
        label: None,
        bind_group_layouts: &[&bind_group_layout],
        push_constant_ranges: &[],
    });
}
```

**Expected vs observed behavior**
I am just getting familiar with WebGPU but I expected the BindGroupLayout to just work, as it is the same device. (I compared them by id and global_id). I get `BindGroupLayout[Id(0,1,mtl)] does not exist`.

**Extra materials**
None

**Platform**
Using wgpu 22.1.0 on Macbook Pro 2021 (M1 Pro) running Sonoma 14.0
Other dependencies for the example are just pollster version 0.3.0

**Comment by ErichDonGubler** [comment] 2024-08-23 14:21
AFAIK, `Device`s returned by different executions of `instance.request_adapter(…).block_on().unwrap().request_device(…).block_on().unwrap()` should be considered different; they should not be able to share resources. @teoxoy or @jimblandy, does that sound right?

Assuming so, I'm not sure why WGPU is returning the same ID; we should be getting different `Device`s with different IDs, which should make the re-usage of `bind_group_layout` in the OP rejected by a validation error.

**Comment by cwfitzgerald** [comment] 2024-08-23 19:23
> Assuming so, I'm not sure why WGPU is returning the same ID; we should be getting different Devices with different IDs, which should make the re-usage of bind_group_layout in the OP rejected by a validation error.

It;s because they are making a new instance, and hence a new hub.

**Comment by teoxoy** [comment] 2024-08-23 19:37
Yes, resources can't be shared between devices.

> It's because they are making a new instance, and hence a new hub.

When `global_id`s are not so global 😅. This will be fixed by https://github.com/gfx-rs/wgpu/pull/6134.

Closing as working as intended.

**Closed as not planned by teoxoy** 2024-08-23 19:37 UTC

**Comment by cwfitzgerald** [comment] 2024-08-23 20:30
Fwiw, the error idnt really helpful, but I think this will get better once hubs are removed.
