### ISSUE TITLE
[macOS] minimized and hidden (cmd+h) leaks memory and blocks.

### ISSUE THREAD

**Issue by seivan** [gfx-rs/wgpu#78] opened 2019-02-26 20:47 UTC
It eventually crashes with ` thread 'main' panicked at 'attempt to add with overflow', wgpu-native/src/swap_chain.rs:177:27`

Reproducible with https://github.com/gfx-rs/wgpu/pull/77  & master

~Fullscreen laggs to the point of unusable - however a maxed out window size works as normal.~
Moved to separate [issue](https://github.com/gfx-rs/wgpu-rs/issues/72) since it no longer leaks memory and seems to be a different problem. 

Memory usage spiked while this issue went up, and did not go away once the window was brought back into focused and not fullscreen - so definitely a leak. 

Edit: Happens with `gfx-hal/quad+SDL|Winit` examples as well. 

Edit: Fix for minimized and hidden is in https://github.com/gfx-rs/gfx/pull/2973

Edit: Seems to have appeared again https://github.com/gfx-rs/wgpu/issues/78#issuecomment-555988632

**Comment by seivan** [comment] 2019-02-26 21:17
Although `Maximized` event doesn't create a new swapchain, the previous event is `Resized(_, _)` and that triggers a new swapchain. 

I also added a new swapchain on `Maximize` just to make sure in case there is a slight delay between those two events, but the issue is still there

```rust
WINDOW EVENT Exposed
WINDOW EVENT Moved(0, 0)
WINDOW EVENT SizeChanged(1920, 1200)
WINDOW EVENT Resized(1920, 1200)
WINDOW EVENT Maximized
RECREATED SWAP CHAIN: 1920 - 1200
```

**Comment by seivan** [comment] 2019-02-26 21:18
Intersting tidbit. Setting sdl's window to fullscreen with the same resolution as native full screen has no issues, it seems to be related to the way Windows are fullscreen-ed on macOS (tapping that green icon)

**Comment by eldyer** [comment] 2019-05-26 05:05
This seems to be not only a macOS issue, it also occurs on my Linux / Vulkan machine. My App doesn't lag, but crashes very often in fullscreen mode (initialization error or out of memory). No problems if I switch back to windowed mode.

**Comment by seivan** [comment] 2019-08-22 19:25
Parts of this is fixed with https://github.com/gfx-rs/gfx/pull/2973
* Minimizing
* Hiding

No longer leaks memory.

* Fullscreen (maximised window) still leaks memory and kill fps.

**Comment by seivan** [comment] 2019-11-20 12:46
@kvark This has resurfaced again. Hiding or minimizing will make it hemorrhage memory. 
I also noticed it never dropping buffers. 
The leak stops temporarily when the window comes into focus again, but the leaks remain. 

 If I hide the window and bring it back up again before capturing these buffers appear, because I am updating buffers every frame.
![](https://files.gitter.im/gfx-rs/webgpu/FTsk/image.png)

Not moving the window out of focus, and capturing will only show the three buffers I am supposed to have.

**Comment by grovesNL** [comment] 2020-11-06 13:53
I just profiled the cube example with Instruments on macOS and the memory usage appears to be stable while minimizing. It's possible this was fixed with some of the changes in the past year or caused by something specific to the environment (e.g. Xcode or the graphics driver retaining objects for a long time), so we can probably close this for now.

If anyone has a case that reproduces minimize-related memory leaks on macOS, please reopen this issue so we could look into it.

**Closed by grovesNL** 2020-11-06 13:53 UTC
Labels: type: bug
